"""
code_bank.py — 코드 타이핑 연습 문제 은행 (빈칸 ____ 채우기).

퀴즈와 동일하게 코스 → 주제(섹터) 구조. 강의자료 기반.
형식: prompt(지시문) / code(____ 포함 코드) / answers(허용 정답 목록)
      / explain(해설) / difficulty(쉬움|보통|어려움)

채점은 프론트에서 공백 정리 + 따옴표 통일 후 answers와 비교한다.
"""
from __future__ import annotations
from typing import Dict, List

CODE_BANK: Dict[str, Dict[str, List[dict]]] = {

"파이썬 입문": {

"파이썬 시작하기": [
    {"prompt": "화면에 Hello Python!! 을 출력하는 함수를 채우세요.",
     "code": "____('Hello Python!!')",
     "answers": ["print"],
     "explain": "print() 함수는 따옴표 안의 문자열을 화면에 출력합니다.",
     "difficulty": "쉬움"},
    {"prompt": "스크립트 파일에서 변수 weight의 값을 출력하도록 채우세요.",
     "code": "weight = 78.2\n____(weight)",
     "answers": ["print"],
     "explain": "스크립트 모드에서는 반드시 print() 함수를 써야 변수의 값이 출력됩니다.",
     "difficulty": "쉬움"},
    {"prompt": "두 문자열을 이어붙여 '안녕하세요'가 출력되게 연산자를 채우세요.",
     "code": "print('안녕' ____ '하세요')",
     "answers": ["+"],
     "explain": "문자열끼리의 + 연산은 두 문자열을 이어붙입니다.",
     "difficulty": "보통"},
],

"변수": [
    {"prompt": "print(x, y) 가 100 200 을 출력하도록 동시할당문을 채우세요.",
     "code": "x, y = ____, 200\nprint(x, y)",
     "answers": ["100"],
     "explain": "동시할당문은 한 줄에서 여러 변수에 값을 순서대로 할당합니다.",
     "difficulty": "쉬움"},
    {"prompt": "두 변수의 값을 한 줄로 맞바꾸도록 채우세요.",
     "code": "a, b = 3, 7\na, b = ____",
     "answers": ["b, a", "b,a"],
     "explain": "a, b = b, a 는 두 변수의 값을 맞바꾸는 파이썬 특유의 문법입니다.",
     "difficulty": "보통"},
    {"prompt": "문자열 s1의 길이를 출력하도록 함수를 채우세요.",
     "code": "s1 = 'Hello'\nprint(____(s1))",
     "answers": ["len"],
     "explain": "len() 함수는 문자열의 길이를 돌려줍니다. 'Hello'는 5입니다.",
     "difficulty": "쉬움"},
    {"prompt": "두 문자열을 합쳐 하나로 만들도록 연산자를 채우세요.",
     "code": "s1 = '파이'\ns2 = '썬'\nprint(s1 ____ s2)",
     "answers": ["+"],
     "explain": "2개의 문자열을 서로 합치려면 + 연산을 사용합니다.",
     "difficulty": "쉬움"},
],

"자료형": [
    {"prompt": "3.14의 자료형을 알아내는 함수를 채우세요.",
     "code": "print(____(3.14))",
     "answers": ["type"],
     "explain": "type() 함수는 변수나 값의 자료형을 알려줍니다. 결과는 float입니다.",
     "difficulty": "쉬움"},
    {"prompt": "문자열 '7'을 정수로 변환해 10이 출력되게 채우세요.",
     "code": "n = ____('7') + 3\nprint(n)",
     "answers": ["int"],
     "explain": "int()는 문자열을 정수로 변환합니다. 7 + 3 = 10이 됩니다.",
     "difficulty": "보통"},
    {"prompt": "숫자 10을 문자열로 변환하도록 채우세요.",
     "code": "s = ____(10)\nprint(s + '점')",
     "answers": ["str"],
     "explain": "str()은 숫자를 문자열로 변환합니다. 변환해야 '10점'처럼 이어붙일 수 있습니다.",
     "difficulty": "보통"},
],

"연산자": [
    {"prompt": "나눗셈의 몫 3이 출력되도록 연산자를 채우세요.",
     "code": "print(7 ____ 2)  # 3",
     "answers": ["//"],
     "explain": "// 는 몫 연산자로 소수점 이하를 버립니다.",
     "difficulty": "쉬움"},
    {"prompt": "나눗셈의 나머지 1이 출력되도록 연산자를 채우세요.",
     "code": "print(7 ____ 2)  # 1",
     "answers": ["%"],
     "explain": "% 는 나머지 연산자입니다.",
     "difficulty": "쉬움"},
    {"prompt": "2의 7제곱(128)이 계산되도록 연산자를 채우세요.",
     "code": "print(2 ____ 7)",
     "answers": ["**"],
     "explain": "** 는 거듭제곱 연산자입니다. 2가 밑, 7이 지수입니다.",
     "difficulty": "쉬움"},
    {"prompt": "x = x + 5 와 같은 뜻이 되도록 복합 할당 연산자를 채우세요.",
     "code": "x = 10\nx ____ 5\nprint(x)  # 15",
     "answers": ["+="],
     "explain": "복합 할당 연산자 += 는 산술 연산과 할당을 결합한 것입니다.",
     "difficulty": "보통"},
    {"prompt": "다음 식의 출력 결과를 직접 적어보세요.",
     "code": "print(2 + 3 * 4)",
     "answers": ["14"],
     "explain": "곱셈이 덧셈보다 우선순위가 높아 3*4=12가 먼저 계산되고 2를 더해 14입니다.",
     "difficulty": "보통"},
],

"모듈": [
    {"prompt": "random 모듈을 사용할 수 있도록 키워드를 채우세요.",
     "code": "____ random\nprint(random.randint(1, 6))",
     "answers": ["import"],
     "explain": "표준 라이브러리 모듈은 import 한 줄로 바로 사용할 수 있습니다.",
     "difficulty": "쉬움"},
    {"prompt": "1부터 6까지의 정수 중 하나를 무작위로 뽑는 함수를 채우세요.",
     "code": "import random\nprint(random.____(1, 6))",
     "answers": ["randint"],
     "explain": "randint(a, b)는 a 이상 b 이하의 정수를 무작위로 돌려줍니다.",
     "difficulty": "보통"},
    {"prompt": "16의 제곱근을 구하는 math 모듈 함수를 채우세요.",
     "code": "import math\nprint(math.____(16))  # 4.0",
     "answers": ["sqrt"],
     "explain": "sqrt()는 제곱근을 구하며 결과는 항상 실수(float)입니다.",
     "difficulty": "보통"},
],
},

"파이썬 중급": {

"조건문": [
    {"prompt": "점수가 60 이상이면 합격이 출력되도록 비교 연산자를 채우세요.",
     "code": "score = 75\nif score ____ 60:\n    print('합격입니다')",
     "answers": [">="],
     "explain": "'이상'은 >= 연산자입니다. 60도 포함됩니다.",
     "difficulty": "쉬움"},
    {"prompt": "앞 조건이 거짓일 때 다른 조건을 검사하는 키워드를 채우세요.",
     "code": "if score >= 90:\n    print('A')\n____ score >= 80:\n    print('B')",
     "answers": ["elif"],
     "explain": "elif는 else if를 합친 키워드로, 추가 조건을 검사합니다.",
     "difficulty": "쉬움"},
    {"prompt": "num이 짝수인지 검사하도록 연산자를 채우세요.",
     "code": "if num % 2 ____ 0:\n    print('짝수입니다')",
     "answers": ["=="],
     "explain": "2로 나눈 나머지가 0과 '같은지'는 비교 연산자 == 로 검사합니다. = 는 할당이라 안 됩니다.",
     "difficulty": "보통"},
    {"prompt": "모든 조건이 거짓일 때 실행될 블록을 만드는 키워드를 채우세요.",
     "code": "if num > 0:\n    print('양수')\n____:\n    print('양수가 아님')",
     "answers": ["else"],
     "explain": "else는 위의 조건이 모두 거짓일 때 실행됩니다. 뒤에 조건 없이 콜론만 붙입니다.",
     "difficulty": "쉬움"},
],

"반복문": [
    {"prompt": "0부터 4까지 5번 반복하도록 함수를 채우세요.",
     "code": "for i in ____(5):\n    print(i)",
     "answers": ["range"],
     "explain": "range(5)는 0, 1, 2, 3, 4의 숫자 시퀀스를 만듭니다.",
     "difficulty": "쉬움"},
    {"prompt": "1부터 10까지 반복되도록 숫자를 채우세요.",
     "code": "for i in range(1, ____):\n    print(i)",
     "answers": ["11"],
     "explain": "range(start, stop)은 stop-1까지 생성하므로 10까지 돌리려면 11이어야 합니다.",
     "difficulty": "보통"},
    {"prompt": "green이 입력되면 무한 루프를 빠져나가도록 키워드를 채우세요.",
     "code": "while True:\n    color = input('색상: ')\n    if color == 'green':\n        ____",
     "answers": ["break"],
     "explain": "break는 가장 가까운 루프를 즉시 빠져나옵니다.",
     "difficulty": "쉬움"},
    {"prompt": "i가 2일 때만 출력을 건너뛰도록 키워드를 채우세요.",
     "code": "for i in range(5):\n    if i == 2:\n        ____\n    print(i)",
     "answers": ["continue"],
     "explain": "continue는 아래 문장만 건너뛰고 반복은 계속합니다. 0 1 3 4가 출력됩니다.",
     "difficulty": "보통"},
    {"prompt": "조건이 항상 참인 무한 루프가 되도록 채우세요.",
     "code": "while ____:\n    print('신호 대기 중')",
     "answers": ["True"],
     "explain": "while True: 는 조건이 항상 참이라 무한히 반복됩니다. 대문자 T에 주의하세요.",
     "difficulty": "쉬움"},
],

"리스트와 튜플": [
    {"prompt": "두 번째 항목 '배'가 출력되도록 인덱스를 채우세요.",
     "code": "fruits = ['사과', '배', '포도']\nprint(fruits[____])",
     "answers": ["1"],
     "explain": "인덱스는 0부터 시작하므로 두 번째 항목은 인덱스 1입니다.",
     "difficulty": "쉬움"},
    {"prompt": "리스트의 맨 마지막 항목이 출력되도록 인덱스를 채우세요.",
     "code": "letters = ['a', 'b', 'c', 'd']\nprint(letters[____])  # d",
     "answers": ["-1", "3"],
     "explain": "음수 인덱스 -1은 맨 끝 항목을 가리킵니다. (인덱스 3도 정답)",
     "difficulty": "보통"},
    {"prompt": "리스트 끝에 'RM'을 추가하는 메소드를 채우세요.",
     "code": "members = ['Jin', 'Suga']\nmembers.____('RM')",
     "answers": ["append"],
     "explain": "append()는 리스트 맨 뒤에 항목 하나를 추가합니다.",
     "difficulty": "쉬움"},
    {"prompt": "[2, 3, 4]가 출력되도록 슬라이싱 끝 인덱스를 채우세요.",
     "code": "nums = [1, 2, 3, 4, 5]\nprint(nums[1:____])",
     "answers": ["4"],
     "explain": "슬라이싱은 끝 인덱스 직전까지입니다. 인덱스 1~3의 값 2, 3, 4가 추출됩니다.",
     "difficulty": "보통"},
    {"prompt": "다음 코드의 출력 결과를 직접 적어보세요.",
     "code": "print(len([10, 20, 30]))",
     "answers": ["3"],
     "explain": "len()은 리스트의 항목 개수를 돌려줍니다.",
     "difficulty": "쉬움"},
],

"딕셔너리와 집합": [
    {"prompt": "수학 점수 85가 출력되도록 키를 채우세요. (따옴표 포함)",
     "code": "score = {'국어': 90, '수학': 85}\nprint(score[____])",
     "answers": ["'수학'", "\"수학\""],
     "explain": "딕셔너리는 키로 값을 찾습니다. 키가 문자열이면 따옴표가 필요합니다.",
     "difficulty": "보통"},
    {"prompt": "딕셔너리의 모든 키를 얻는 메소드를 채우세요.",
     "code": "phone_book = {'홍길동': '010-1234'}\nprint(phone_book.____())",
     "answers": ["keys"],
     "explain": "keys()는 모든 키, values()는 모든 값, items()는 (키, 값) 쌍을 돌려줍니다.",
     "difficulty": "보통"},
    {"prompt": "집합에 요소 4를 추가하는 메소드를 채우세요.",
     "code": "s = {1, 2, 3}\ns.____(4)",
     "answers": ["add"],
     "explain": "집합은 add()로 요소를 추가합니다. append()는 리스트 전용입니다.",
     "difficulty": "쉬움"},
    {"prompt": "두 집합의 교집합 {2, 3}이 나오도록 연산자를 채우세요.",
     "code": "a = {1, 2, 3}\nb = {2, 3, 4}\nprint(a ____ b)",
     "answers": ["&"],
     "explain": "교집합은 & 연산자(또는 intersection 메소드)를 사용합니다.",
     "difficulty": "보통"},
    {"prompt": "비어 있는 집합을 만들도록 채우세요.",
     "code": "s = ____()",
     "answers": ["set"],
     "explain": "빈 중괄호 { }는 딕셔너리가 되므로, 빈 집합은 set() 함수로 만들어야 합니다.",
     "difficulty": "어려움"},
],
},

"파이썬 고급 v1": {

"함수 기초": [
    {"prompt": "인사를 출력하는 함수를 정의하는 키워드를 채우세요.",
     "code": "____ greet():\n    print('안녕하세요')",
     "answers": ["def"],
     "explain": "def 키워드로 함수를 정의합니다. 함수 이름 뒤에 소괄호와 콜론을 붙입니다.",
     "difficulty": "쉬움"},
    {"prompt": "정의한 greet 함수를 호출하는 코드를 직접 적어보세요.",
     "code": "def greet():\n    print('안녕하세요')\n\n____",
     "answers": ["greet()"],
     "explain": "함수는 이름과 소괄호로 호출해야 안의 코드가 실행됩니다.",
     "difficulty": "쉬움"},
],

"인자와 반환값": [
    {"prompt": "원의 면적을 돌려주도록 키워드를 채우세요.",
     "code": "def area(radius):\n    ____ 3.14 * radius ** 2",
     "answers": ["return"],
     "explain": "return은 함수의 결과(반환값)를 호출한 곳으로 돌려줍니다.",
     "difficulty": "쉬움"},
    {"prompt": "area 함수를 호출해 반환값을 c_area에 저장하도록 채우세요.",
     "code": "def area(radius):\n    return 3.14 * radius ** 2\n\nc_area = ____(5)",
     "answers": ["area"],
     "explain": "호출문을 할당문에 넣으면 반환값 78.5가 변수에 저장됩니다.",
     "difficulty": "보통"},
    {"prompt": "다음 코드의 출력 결과를 직접 적어보세요.",
     "code": "def get_sum(start, end):\n    total = 0\n    for i in range(start, end + 1):\n        total += i\n    return total\n\nprint(get_sum(1, 10))",
     "answers": ["55"],
     "explain": "1부터 10까지의 합이 반환됩니다. 1+2+…+10 = 55입니다.",
     "difficulty": "어려움"},
],

"변수의 범위와 디폴트 인자": [
    {"prompt": "함수 안에서 전역 변수 counter를 사용하도록 키워드를 채우세요.",
     "code": "counter = 100\ndef add():\n    ____ counter\n    counter = counter + 1",
     "answers": ["global"],
     "explain": "global 선언을 해야 함수 내부에서 전역 변수의 값을 바꿀 수 있습니다.",
     "difficulty": "보통"},
    {"prompt": "pickle 매개변수가 기본값 True를 갖도록 채우세요.",
     "code": "def order(pickle=____, onion=True):\n    print(pickle, onion)",
     "answers": ["True"],
     "explain": "매개변수에 기본값을 주는 것이 디폴트 인자입니다. 인자를 생략하면 이 값이 쓰입니다.",
     "difficulty": "보통"},
    {"prompt": "지수를 키워드 인자로 명시하도록 채우세요. (밑 2, 지수 10)",
     "code": "power(base=2, ____=10)",
     "answers": ["exponent"],
     "explain": "키워드 인자는 매개변수 이름을 명시해 순서 혼동을 막습니다.",
     "difficulty": "어려움"},
],

"판다스와 CSV": [
    {"prompt": "판다스를 pd라는 별칭으로 불러오도록 키워드를 채우세요.",
     "code": "import pandas ____ pd",
     "answers": ["as"],
     "explain": "import ~ as 별칭 구문입니다. 판다스는 관례적으로 pd를 씁니다.",
     "difficulty": "쉬움"},
    {"prompt": "CSV 파일을 읽어 데이터프레임으로 만드는 함수를 채우세요.",
     "code": "import pandas as pd\ndf = pd.____('countries.csv')",
     "answers": ["read_csv"],
     "explain": "read_csv() 한 줄이면 CSV가 데이터프레임으로 변환됩니다.",
     "difficulty": "보통"},
    {"prompt": "csv 모듈로 읽을 때 헤더(첫 줄)를 건너뛰는 함수를 채우세요.",
     "code": "reader = csv.reader(f)\nheader = ____(reader)",
     "answers": ["next"],
     "explain": "next()를 한 번 호출하면 첫 행(헤더)을 건너뛰고 데이터부터 읽습니다.",
     "difficulty": "어려움"},
],

"데이터프레임 다루기": [
    {"prompt": "데이터프레임의 처음 5행을 보는 메소드를 채우세요.",
     "code": "df.____()",
     "answers": ["head"],
     "explain": "head()는 처음 5행, tail()은 마지막 5행을 가져옵니다.",
     "difficulty": "쉬움"},
    {"prompt": "데이터 특징을 한 번에 요약하는 메소드를 채우세요.",
     "code": "df.____()",
     "answers": ["describe"],
     "explain": "describe()는 평균·표준편차·최솟값·최댓값 등을 한 번에 요약합니다.",
     "difficulty": "보통"},
    {"prompt": "결손값을 0으로 채우는 메소드를 채우세요.",
     "code": "weather.____(0, inplace=True)",
     "answers": ["fillna"],
     "explain": "fillna()가 결손값을 채우고, inplace=True로 원본에 반영합니다.",
     "difficulty": "보통"},
    {"prompt": "'인구' 열 기준으로 정렬하는 메소드를 채우세요.",
     "code": "df.____('인구')",
     "answers": ["sort_values"],
     "explain": "sort_values()에 정렬할 열의 이름을 넘기면 됩니다.",
     "difficulty": "어려움"},
],
},

"파이썬 고급 v2": {

"넘파이 기초": [
    {"prompt": "넘파이를 관례적인 별칭으로 불러오도록 채우세요.",
     "code": "import numpy as ____",
     "answers": ["np"],
     "explain": "전 세계 개발자들이 약속처럼 np라는 별칭을 사용합니다.",
     "difficulty": "쉬움"},
    {"prompt": "리스트로부터 넘파이 배열을 만드는 함수를 채우세요.",
     "code": "import numpy as np\nmid = np.____([10, 20, 30])",
     "answers": ["array"],
     "explain": "np.array()는 리스트를 넘파이 배열(ndarray)로 만듭니다.",
     "difficulty": "쉬움"},
    {"prompt": "학생별 총점(벡터합)이 계산되도록 연산자를 채우세요.",
     "code": "total = mid_scores ____ final_scores",
     "answers": ["+"],
     "explain": "넘파이 배열의 + 는 같은 위치의 원소끼리 더하는 벡터합 연산입니다.",
     "difficulty": "보통"},
],

"배열 속성과 연산": [
    {"prompt": "모든 직원의 월급에 100을 더하도록 연산자를 채우세요.",
     "code": "salary = np.array([220, 250, 230])\nsalary = salary ____ 100",
     "answers": ["+"],
     "explain": "배열에 수를 더하면 모든 요소에 한 번에 더해집니다.",
     "difficulty": "쉬움"},
    {"prompt": "반복문 없이 배열 전체의 합을 구하는 함수를 채우세요.",
     "code": "result = np.____(arr)",
     "answers": ["sum"],
     "explain": "np.sum()은 벡터화 연산으로 반복문보다 수십 배 빠릅니다.",
     "difficulty": "보통"},
],

"인덱싱과 슬라이싱": [
    {"prompt": "0번째 행, 2번째 열의 요소를 꺼내도록 인덱스를 채우세요.",
     "code": "np_array[0, ____]",
     "answers": ["2"],
     "explain": "넘파이 2차원 배열은 [행, 열] 콤마 표기로 접근합니다.",
     "difficulty": "보통"},
    {"prompt": "20살 초과인 값만 추려내도록 비교 연산자를 채우세요.",
     "code": "ages = np.array([18, 25, 30])\nprint(ages[ages ____ 20])",
     "answers": [">"],
     "explain": "조건식으로 부울 배열을 만들어 대괄호에 넣는 논리 인덱싱입니다.",
     "difficulty": "보통"},
    {"prompt": "짝수만 추려내도록 비교 연산자를 채우세요.",
     "code": "print(arr[arr % 2 ____ 0])",
     "answers": ["=="],
     "explain": "%2가 0과 같은 위치만 True가 되어 짝수만 추려집니다.",
     "difficulty": "어려움"},
],

"배열 생성 함수": [
    {"prompt": "0에서 10까지 균일한 간격의 수 100개를 만드는 함수를 채우세요.",
     "code": "x = np.____(0, 10, 100)",
     "answers": ["linspace"],
     "explain": "linspace(시작, 끝, 개수)는 균일 간격의 배열을 생성합니다.",
     "difficulty": "보통"},
    {"prompt": "12개의 데이터를 3행 4열로 바꾸는 메소드를 채우세요.",
     "code": "arr = np.arange(12)\nm = arr.____(3, 4)",
     "answers": ["reshape"],
     "explain": "reshape()는 데이터 개수는 유지한 채 배열의 형태만 바꿉니다.",
     "difficulty": "쉬움"},
    {"prompt": "고차원 배열을 1차원으로 펴는 메소드를 채우세요.",
     "code": "flat = m.____()",
     "answers": ["flatten"],
     "explain": "flatten()은 2차원 이상의 배열을 1차원으로 만드는 평탄화 함수입니다.",
     "difficulty": "보통"},
],

"난수와 통계": [
    {"prompt": "평균 175, 표준편차 10인 정규분포 난수 10000개를 만드는 함수를 채우세요.",
     "code": "heights = np.random.____(175, 10, 10000)",
     "answers": ["normal"],
     "explain": "normal(평균, 표준편차, 개수)은 정규분포를 따르는 난수를 생성합니다.",
     "difficulty": "보통"},
    {"prompt": "1부터 10 사이의 정수 난수를 4행 7열로 만드는 함수를 채우세요.",
     "code": "nums = np.random.____(1, 11, (4, 7))",
     "answers": ["randint"],
     "explain": "randint(시작, 끝+1, 모양)으로 정수 난수 배열을 만듭니다.",
     "difficulty": "보통"},
    {"prompt": "두 데이터의 상관관계를 계산하는 함수를 채우세요.",
     "code": "r = np.____(x, y)",
     "answers": ["corrcoef"],
     "explain": "corrcoef(x, y)는 요소들의 상관관계(상관계수)를 계산합니다.",
     "difficulty": "어려움"},
],
},
}
