"""
live_bank.py — 실전 코딩 문제 은행 (전체 코드 작성 + 브라우저 실행 채점).

채점은 프론트의 Pyodide(브라우저 내 파이썬)가 수행한다:
  1. 사용자가 작성한 코드를 exec
  2. tests의 call을 eval 해서 expected(repr 문자열)와 비교
     - 넘파이 배열은 tolist()로 변환 후 비교
     - 실수는 오차 허용(isclose) 비교

형식: prompt / starter(시작 코드) / tests[{call, expected}]
      / solution(참고 정답) / needs(필요 패키지) / difficulty / topic
"""
from __future__ import annotations
from typing import Dict, List

LIVE_BANK: Dict[str, List[dict]] = {

"파이썬 입문": [
    {"topic": "변수와 문자열", "difficulty": "쉬움",
     "prompt": "이름을 받아 '안녕하세요, OO님!' 형태의 문자열을 반환하는 함수 greet(name)을 작성하세요.",
     "starter": "def greet(name):\n    # 여기에 작성하세요\n    ",
     "tests": [
         {"call": "greet('한성')", "expected": "'안녕하세요, 한성님!'"},
         {"call": "greet('부기')", "expected": "'안녕하세요, 부기님!'"},
     ],
     "solution": "def greet(name):\n    return '안녕하세요, ' + name + '님!'"},
    {"topic": "변수와 문자열", "difficulty": "쉬움",
     "prompt": "성과 이름을 받아 붙여서 반환하는 함수 join_name(last, first)를 작성하세요.",
     "starter": "def join_name(last, first):\n    # 문자열 + 연산을 사용하세요\n    ",
     "tests": [
         {"call": "join_name('홍', '길동')", "expected": "'홍길동'"},
         {"call": "join_name('김', '철수')", "expected": "'김철수'"},
     ],
     "solution": "def join_name(last, first):\n    return last + first"},
    {"topic": "변수와 문자열", "difficulty": "쉬움",
     "prompt": "이름을 받아 글자 수를 반환하는 함수 name_length(name)를 작성하세요.",
     "starter": "def name_length(name):\n    # len() 함수를 사용하세요\n    ",
     "tests": [
         {"call": "name_length('Hello')", "expected": "5"},
         {"call": "name_length('한성대')", "expected": "3"},
     ],
     "solution": "def name_length(name):\n    return len(name)"},
    {"topic": "변수와 문자열", "difficulty": "보통",
     "prompt": "두 변수의 값을 맞바꿔 (b, a) 순서의 튜플로 반환하는 함수 swap(a, b)를 작성하세요.",
     "starter": "def swap(a, b):\n    # 동시할당 a, b = b, a 를 떠올려 보세요\n    ",
     "tests": [
         {"call": "swap(3, 7)", "expected": "(7, 3)"},
         {"call": "swap('x', 'y')", "expected": "('y', 'x')"},
     ],
     "solution": "def swap(a, b):\n    a, b = b, a\n    return a, b"},
    {"topic": "자료형", "difficulty": "보통",
     "prompt": "숫자로 된 문자열 두 개를 받아 정수로 변환한 합을 반환하는 함수 str_sum(s1, s2)을 작성하세요.",
     "starter": "def str_sum(s1, s2):\n    # int() 변환을 잊지 마세요\n    ",
     "tests": [
         {"call": "str_sum('7', '3')", "expected": "10"},
         {"call": "str_sum('100', '200')", "expected": "300"},
     ],
     "solution": "def str_sum(s1, s2):\n    return int(s1) + int(s2)"},
    {"topic": "자료형", "difficulty": "보통",
     "prompt": "점수(정수)를 받아 '10점' 처럼 문자열로 만들어 반환하는 함수 score_text(n)를 작성하세요.",
     "starter": "def score_text(n):\n    # str() 변환 후 이어붙이세요\n    ",
     "tests": [
         {"call": "score_text(10)", "expected": "'10점'"},
         {"call": "score_text(95)", "expected": "'95점'"},
     ],
     "solution": "def score_text(n):\n    return str(n) + '점'"},
    {"topic": "연산자", "difficulty": "쉬움",
     "prompt": "반지름 r를 받아 원의 면적(3.14 * r * r)을 반환하는 함수 circle_area(r)를 작성하세요.",
     "starter": "def circle_area(r):\n    # 여기에 작성하세요\n    ",
     "tests": [
         {"call": "circle_area(5)", "expected": "78.5"},
         {"call": "circle_area(1)", "expected": "3.14"},
     ],
     "solution": "def circle_area(r):\n    return 3.14 * r * r"},
    {"topic": "연산자", "difficulty": "보통",
     "prompt": "두 정수 a, b를 받아 (몫, 나머지) 튜플을 반환하는 함수 divide(a, b)를 작성하세요.",
     "starter": "def divide(a, b):\n    # // 와 % 를 사용해 보세요\n    ",
     "tests": [
         {"call": "divide(7, 2)", "expected": "(3, 1)"},
         {"call": "divide(10, 3)", "expected": "(3, 1)"},
         {"call": "divide(8, 4)", "expected": "(2, 0)"},
     ],
     "solution": "def divide(a, b):\n    return a // b, a % b"},
    {"topic": "연산자", "difficulty": "쉬움",
     "prompt": "밑과 지수를 받아 거듭제곱을 반환하는 함수 power(base, exp)를 작성하세요.",
     "starter": "def power(base, exp):\n    # ** 연산자를 사용하세요\n    ",
     "tests": [
         {"call": "power(2, 7)", "expected": "128"},
         {"call": "power(3, 2)", "expected": "9"},
     ],
     "solution": "def power(base, exp):\n    return base ** exp"},
    {"topic": "연산자", "difficulty": "보통",
     "prompt": "두 수의 평균을 반환하는 함수 average(a, b)를 작성하세요. (/ 연산은 항상 실수!)",
     "starter": "def average(a, b):\n    # 여기에 작성하세요\n    ",
     "tests": [
         {"call": "average(4, 6)", "expected": "5.0"},
         {"call": "average(3, 4)", "expected": "3.5"},
     ],
     "solution": "def average(a, b):\n    return (a + b) / 2"},
    {"topic": "연산자", "difficulty": "보통",
     "prompt": "두 문자열의 길이 합을 반환하는 함수 total_len(s1, s2)을 작성하세요.",
     "starter": "def total_len(s1, s2):\n    # len() 을 두 번 사용하세요\n    ",
     "tests": [
         {"call": "total_len('hi', 'python')", "expected": "8"},
         {"call": "total_len('한성', '대학교')", "expected": "5"},
     ],
     "solution": "def total_len(s1, s2):\n    return len(s1) + len(s2)"},
    {"topic": "모듈", "difficulty": "어려움",
     "prompt": "직각삼각형의 두 변 a, b를 받아 빗변 길이를 반환하는 함수 hypotenuse(a, b)를 작성하세요. (math.sqrt 활용 — 피타고라스 정리)",
     "starter": "import math\n\ndef hypotenuse(a, b):\n    # a² + b² 의 제곱근\n    ",
     "tests": [
         {"call": "hypotenuse(3, 4)", "expected": "5.0"},
         {"call": "hypotenuse(6, 8)", "expected": "10.0"},
     ],
     "solution": "import math\n\ndef hypotenuse(a, b):\n    return math.sqrt(a * a + b * b)"},
    {"topic": "모듈", "difficulty": "보통",
     "prompt": "주사위처럼 1부터 6 사이의 정수를 무작위로 반환하는 함수 dice()를 작성하세요. (random.randint 활용)",
     "starter": "import random\n\ndef dice():\n    # randint(1, 6)\n    ",
     "tests": [
         {"call": "dice() in [1, 2, 3, 4, 5, 6]", "expected": "True"},
         {"call": "dice() in [1, 2, 3, 4, 5, 6]", "expected": "True"},
         {"call": "type(dice()).__name__", "expected": "'int'"},
     ],
     "solution": "import random\n\ndef dice():\n    return random.randint(1, 6)"},
],

"파이썬 중급": [
    {"topic": "조건문", "difficulty": "쉬움",
     "prompt": "정수가 짝수면 True, 홀수면 False를 반환하는 함수 is_even(n)을 작성하세요.",
     "starter": "def is_even(n):\n    # n % 2 == 0 을 활용하세요\n    ",
     "tests": [
         {"call": "is_even(4)", "expected": "True"},
         {"call": "is_even(7)", "expected": "False"},
         {"call": "is_even(0)", "expected": "True"},
     ],
     "solution": "def is_even(n):\n    return n % 2 == 0"},
    {"topic": "조건문", "difficulty": "보통",
     "prompt": "점수를 받아 90 이상 'A', 80 이상 'B', 60 이상 'C', 그 외 'F'를 반환하는 함수 grade(score)를 작성하세요.",
     "starter": "def grade(score):\n    # if-elif-else 를 사용하세요\n    ",
     "tests": [
         {"call": "grade(95)", "expected": "'A'"},
         {"call": "grade(85)", "expected": "'B'"},
         {"call": "grade(70)", "expected": "'C'"},
         {"call": "grade(50)", "expected": "'F'"},
     ],
     "solution": "def grade(score):\n    if score >= 90:\n        return 'A'\n    elif score >= 80:\n        return 'B'\n    elif score >= 60:\n        return 'C'\n    else:\n        return 'F'"},
    {"topic": "조건문", "difficulty": "보통",
     "prompt": "정수의 절댓값을 반환하는 함수 abs_value(n)를 작성하세요. (abs() 말고 if-else로!)",
     "starter": "def abs_value(n):\n    # 음수면 부호를 바꿔 주세요\n    ",
     "tests": [
         {"call": "abs_value(-5)", "expected": "5"},
         {"call": "abs_value(3)", "expected": "3"},
         {"call": "abs_value(0)", "expected": "0"},
     ],
     "solution": "def abs_value(n):\n    if n < 0:\n        return -n\n    else:\n        return n"},
    {"topic": "반복문", "difficulty": "보통",
     "prompt": "1부터 n까지의 합을 반복문으로 계산해 반환하는 함수 sum_to(n)을 작성하세요.",
     "starter": "def sum_to(n):\n    total = 0\n    # for 또는 while 로 반복하세요\n    ",
     "tests": [
         {"call": "sum_to(10)", "expected": "55"},
         {"call": "sum_to(100)", "expected": "5050"},
         {"call": "sum_to(1)", "expected": "1"},
     ],
     "solution": "def sum_to(n):\n    total = 0\n    for i in range(1, n + 1):\n        total += i\n    return total"},
    {"topic": "반복문", "difficulty": "보통",
     "prompt": "n부터 1까지 거꾸로 담긴 리스트를 반환하는 함수 count_down(n)을 작성하세요.",
     "starter": "def count_down(n):\n    result = []\n    # while 또는 range(n, 0, -1) 활용\n    ",
     "tests": [
         {"call": "count_down(3)", "expected": "[3, 2, 1]"},
         {"call": "count_down(1)", "expected": "[1]"},
         {"call": "count_down(5)", "expected": "[5, 4, 3, 2, 1]"},
     ],
     "solution": "def count_down(n):\n    result = []\n    for i in range(n, 0, -1):\n        result.append(i)\n    return result"},
    {"topic": "반복문", "difficulty": "어려움",
     "prompt": "반복문으로 리스트의 최댓값을 찾아 반환하는 함수 max_of(nums)를 작성하세요. (max() 함수 없이!)",
     "starter": "def max_of(nums):\n    biggest = nums[0]\n    # 하나씩 비교하며 갱신하세요\n    ",
     "tests": [
         {"call": "max_of([3, 1, 2])", "expected": "3"},
         {"call": "max_of([5])", "expected": "5"},
         {"call": "max_of([-2, -7, -1])", "expected": "-1"},
     ],
     "solution": "def max_of(nums):\n    biggest = nums[0]\n    for n in nums:\n        if n > biggest:\n            biggest = n\n    return biggest"},
    {"topic": "리스트", "difficulty": "보통",
     "prompt": "정수 리스트에서 짝수의 개수를 세어 반환하는 함수 count_even(nums)를 작성하세요.",
     "starter": "def count_even(nums):\n    # % 2 == 0 으로 짝수를 판별하세요\n    ",
     "tests": [
         {"call": "count_even([1, 2, 3, 4])", "expected": "2"},
         {"call": "count_even([1, 3, 5])", "expected": "0"},
         {"call": "count_even([2, 4, 6, 8])", "expected": "4"},
     ],
     "solution": "def count_even(nums):\n    count = 0\n    for n in nums:\n        if n % 2 == 0:\n            count += 1\n    return count"},
    {"topic": "리스트", "difficulty": "쉬움",
     "prompt": "리스트의 첫 항목과 마지막 항목을 튜플로 반환하는 함수 first_last(lst)를 작성하세요. (음수 인덱스 활용)",
     "starter": "def first_last(lst):\n    # 인덱스 0 과 -1\n    ",
     "tests": [
         {"call": "first_last(['a', 'b', 'c'])", "expected": "('a', 'c')"},
         {"call": "first_last([10, 20, 30, 40])", "expected": "(10, 40)"},
     ],
     "solution": "def first_last(lst):\n    return lst[0], lst[-1]"},
    {"topic": "리스트", "difficulty": "쉬움",
     "prompt": "리스트 끝에 항목을 추가한 뒤 그 리스트를 반환하는 함수 add_item(lst, x)를 작성하세요.",
     "starter": "def add_item(lst, x):\n    # append() 를 사용하세요\n    ",
     "tests": [
         {"call": "add_item([1, 2], 3)", "expected": "[1, 2, 3]"},
         {"call": "add_item([], 'RM')", "expected": "['RM']"},
     ],
     "solution": "def add_item(lst, x):\n    lst.append(x)\n    return lst"},
    {"topic": "리스트", "difficulty": "어려움",
     "prompt": "1부터 n까지 각 수의 제곱 리스트를 반환하는 함수 squares(n)를 작성하세요. (리스트 함축 추천)",
     "starter": "def squares(n):\n    # [식 for i in range(1, n + 1)]\n    ",
     "tests": [
         {"call": "squares(3)", "expected": "[1, 4, 9]"},
         {"call": "squares(5)", "expected": "[1, 4, 9, 16, 25]"},
     ],
     "solution": "def squares(n):\n    return [i * i for i in range(1, n + 1)]"},
    {"topic": "리스트", "difficulty": "어려움",
     "prompt": "단어 리스트를 받아 각 단어의 길이 리스트를 반환하는 함수 word_lengths(words)를 작성하세요.",
     "starter": "def word_lengths(words):\n    # 리스트 함축을 써 보세요\n    ",
     "tests": [
         {"call": "word_lengths(['hi', 'python'])", "expected": "[2, 6]"},
         {"call": "word_lengths(['a', 'ab', 'abc'])", "expected": "[1, 2, 3]"},
     ],
     "solution": "def word_lengths(words):\n    return [len(w) for w in words]"},
    {"topic": "딕셔너리와 집합", "difficulty": "쉬움",
     "prompt": "딕셔너리와 키를 받아 해당 값을 반환하는 함수 get_value(d, key)를 작성하세요.",
     "starter": "def get_value(d, key):\n    # 대괄호로 키에 접근하세요\n    ",
     "tests": [
         {"call": "get_value({'국어': 90, '수학': 85}, '수학')", "expected": "85"},
         {"call": "get_value({'a': 1}, 'a')", "expected": "1"},
     ],
     "solution": "def get_value(d, key):\n    return d[key]"},
    {"topic": "딕셔너리와 집합", "difficulty": "보통",
     "prompt": "리스트에서 중복을 제거한 항목의 개수를 반환하는 함수 unique_count(lst)를 작성하세요. (집합 활용)",
     "starter": "def unique_count(lst):\n    # set() 으로 바꾸면 중복이 사라져요\n    ",
     "tests": [
         {"call": "unique_count([1, 2, 2, 3, 3, 3])", "expected": "3"},
         {"call": "unique_count(['a', 'a', 'b'])", "expected": "2"},
     ],
     "solution": "def unique_count(lst):\n    return len(set(lst))"},
    {"topic": "딕셔너리와 집합", "difficulty": "어려움",
     "prompt": "두 리스트의 공통 원소를 정렬된 리스트로 반환하는 함수 common(a, b)을 작성하세요. (교집합 & 활용)",
     "starter": "def common(a, b):\n    # set(a) & set(b) 후 sorted()\n    ",
     "tests": [
         {"call": "common([1, 2, 3], [2, 3, 4])", "expected": "[2, 3]"},
         {"call": "common([1, 5], [2, 6])", "expected": "[]"},
     ],
     "solution": "def common(a, b):\n    return sorted(set(a) & set(b))"},
],

"파이썬 고급 v1": [
    {"topic": "인자와 반환값", "difficulty": "보통",
     "prompt": "start부터 end까지의 합을 반환하는 함수 get_sum(start, end)을 작성하세요.",
     "starter": "def get_sum(start, end):\n    # range(start, end + 1) 에 주의하세요\n    ",
     "tests": [
         {"call": "get_sum(1, 10)", "expected": "55"},
         {"call": "get_sum(5, 7)", "expected": "18"},
     ],
     "solution": "def get_sum(start, end):\n    total = 0\n    for i in range(start, end + 1):\n        total += i\n    return total"},
    {"topic": "인자와 반환값", "difficulty": "보통",
     "prompt": "두 수를 받아 (합, 차, 곱) 세 값을 한 번에 반환하는 함수 calc(a, b)를 작성하세요.",
     "starter": "def calc(a, b):\n    # return 값1, 값2, 값3 형태\n    ",
     "tests": [
         {"call": "calc(4, 2)", "expected": "(6, 2, 8)"},
         {"call": "calc(10, 5)", "expected": "(15, 5, 50)"},
     ],
     "solution": "def calc(a, b):\n    return a + b, a - b, a * b"},
    {"topic": "인자와 반환값", "difficulty": "보통",
     "prompt": "리스트의 (최솟값, 최댓값)을 튜플로 반환하는 함수 min_max(nums)를 작성하세요.",
     "starter": "def min_max(nums):\n    # min(), max() 내장 함수 활용\n    ",
     "tests": [
         {"call": "min_max([3, 1, 2])", "expected": "(1, 3)"},
         {"call": "min_max([10])", "expected": "(10, 10)"},
     ],
     "solution": "def min_max(nums):\n    return min(nums), max(nums)"},
    {"topic": "디폴트 인자", "difficulty": "보통",
     "prompt": "버거 이름과 피클 여부(기본값 True)를 받아 (버거, 피클여부) 튜플을 반환하는 함수 order(burger, pickle=True)를 작성하세요.",
     "starter": "def order(burger, pickle=True):\n    # 디폴트 인자를 그대로 활용하세요\n    ",
     "tests": [
         {"call": "order('불고기버거')", "expected": "('불고기버거', True)"},
         {"call": "order('치즈버거', False)", "expected": "('치즈버거', False)"},
     ],
     "solution": "def order(burger, pickle=True):\n    return burger, pickle"},
    {"topic": "디폴트 인자", "difficulty": "보통",
     "prompt": "이름(기본값 '학생')을 받아 '안녕하세요, OO님!'을 반환하는 함수 greet_default(name='학생')를 작성하세요.",
     "starter": "def greet_default(name='학생'):\n    # 인자가 없으면 기본값이 쓰여요\n    ",
     "tests": [
         {"call": "greet_default()", "expected": "'안녕하세요, 학생님!'"},
         {"call": "greet_default('부기')", "expected": "'안녕하세요, 부기님!'"},
     ],
     "solution": "def greet_default(name='학생'):\n    return '안녕하세요, ' + name + '님!'"},
    {"topic": "디폴트 인자", "difficulty": "어려움",
     "prompt": "이름과 도메인(기본값 'hansung.ac.kr')으로 이메일 주소를 만드는 함수 make_email(name, domain='hansung.ac.kr')를 작성하세요.",
     "starter": "def make_email(name, domain='hansung.ac.kr'):\n    # name + '@' + domain\n    ",
     "tests": [
         {"call": "make_email('swhs015')", "expected": "'swhs015@hansung.ac.kr'"},
         {"call": "make_email('kim', 'naver.com')", "expected": "'kim@naver.com'"},
     ],
     "solution": "def make_email(name, domain='hansung.ac.kr'):\n    return name + '@' + domain"},
    {"topic": "디폴트 인자", "difficulty": "보통",
     "prompt": "키워드 인자로 호출해도 동작하는 거듭제곱 함수 power_kw(base, exponent)를 작성하세요.",
     "starter": "def power_kw(base, exponent):\n    # base ** exponent\n    ",
     "tests": [
         {"call": "power_kw(base=2, exponent=10)", "expected": "1024"},
         {"call": "power_kw(exponent=2, base=3)", "expected": "9"},
     ],
     "solution": "def power_kw(base, exponent):\n    return base ** exponent"},
    {"topic": "디폴트 인자", "difficulty": "보통",
     "prompt": "가격 리스트와 할인액(기본값 0)을 받아 (합계 - 할인액)을 반환하는 함수 total_price(prices, discount=0)를 작성하세요.",
     "starter": "def total_price(prices, discount=0):\n    # sum() 내장 함수 활용\n    ",
     "tests": [
         {"call": "total_price([100, 200])", "expected": "300"},
         {"call": "total_price([100, 200], 50)", "expected": "250"},
     ],
     "solution": "def total_price(prices, discount=0):\n    return sum(prices) - discount"},
    {"topic": "재귀 함수", "difficulty": "어려움",
     "prompt": "재귀 호출로 n!(팩토리얼)을 계산하는 함수 factorial(n)을 작성하세요. (1! = 1이 종료 조건)",
     "starter": "def factorial(n):\n    # 자기 자신을 호출해 보세요\n    ",
     "tests": [
         {"call": "factorial(5)", "expected": "120"},
         {"call": "factorial(1)", "expected": "1"},
         {"call": "factorial(3)", "expected": "6"},
     ],
     "solution": "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)"},
    {"topic": "재귀 함수", "difficulty": "어려움",
     "prompt": "재귀로 피보나치 수열의 n번째 값을 반환하는 함수 fib(n)을 작성하세요. (fib(1)=1, fib(2)=1)",
     "starter": "def fib(n):\n    # n이 2 이하면 1을 반환 (종료 조건)\n    ",
     "tests": [
         {"call": "fib(1)", "expected": "1"},
         {"call": "fib(2)", "expected": "1"},
         {"call": "fib(6)", "expected": "8"},
     ],
     "solution": "def fib(n):\n    if n <= 2:\n        return 1\n    return fib(n - 1) + fib(n - 2)"},
    {"topic": "함수 기초", "difficulty": "쉬움",
     "prompt": "호출할 때마다 문자열 '한성대학교'를 반환하는 함수 school()을 작성하세요.",
     "starter": "def school():\n    # return 만 있으면 돼요\n    ",
     "tests": [
         {"call": "school()", "expected": "'한성대학교'"},
         {"call": "school() + ' 만세'", "expected": "'한성대학교 만세'"},
     ],
     "solution": "def school():\n    return '한성대학교'"},
    {"topic": "함수 기초", "difficulty": "쉬움",
     "prompt": "주소 문자열을 n번 담은 리스트를 반환하는 함수 repeat_address(addr, n)를 작성하세요.",
     "starter": "def repeat_address(addr, n):\n    result = []\n    # n번 반복해 append 하세요\n    ",
     "tests": [
         {"call": "repeat_address('서울시 성북구', 3)", "expected": "['서울시 성북구', '서울시 성북구', '서울시 성북구']"},
         {"call": "repeat_address('A', 1)", "expected": "['A']"},
     ],
     "solution": "def repeat_address(addr, n):\n    result = []\n    for _ in range(n):\n        result.append(addr)\n    return result"},
],

"파이썬 고급 v2": [
    {"topic": "넘파이 기초", "difficulty": "보통", "needs": ["numpy"],
     "prompt": "두 리스트를 넘파이 배열로 바꿔 벡터합을 구한 뒤, 리스트로 변환해 반환하는 함수 add_arrays(a, b)를 작성하세요.",
     "starter": "import numpy as np\n\ndef add_arrays(a, b):\n    # np.array() 변환 → 더하기 → .tolist()\n    ",
     "tests": [
         {"call": "add_arrays([10, 20], [30, 40])", "expected": "[40, 60]"},
         {"call": "add_arrays([1, 2, 3], [4, 5, 6])", "expected": "[5, 7, 9]"},
     ],
     "solution": "import numpy as np\n\ndef add_arrays(a, b):\n    return (np.array(a) + np.array(b)).tolist()"},
    {"topic": "넘파이 기초", "difficulty": "보통", "needs": ["numpy"],
     "prompt": "리스트의 모든 요소를 2배로 만든 리스트를 반환하는 함수 double_all(nums)를 작성하세요. (넘파이 활용)",
     "starter": "import numpy as np\n\ndef double_all(nums):\n    # 배열에 2를 곱하면 끝\n    ",
     "tests": [
         {"call": "double_all([1, 2, 3])", "expected": "[2, 4, 6]"},
         {"call": "double_all([10])", "expected": "[20]"},
     ],
     "solution": "import numpy as np\n\ndef double_all(nums):\n    return (np.array(nums) * 2).tolist()"},
    {"topic": "배열 연산", "difficulty": "보통", "needs": ["numpy"],
     "prompt": "월급 리스트와 인상액을 받아 모든 요소에 인상액을 더한 리스트를 반환하는 함수 raise_salary(salary, amount)를 작성하세요.",
     "starter": "import numpy as np\n\ndef raise_salary(salary, amount):\n    # 배열에 수를 더하면 모든 요소에 적용돼요\n    ",
     "tests": [
         {"call": "raise_salary([220, 250, 230], 100)", "expected": "[320, 350, 330]"},
         {"call": "raise_salary([100], 50)", "expected": "[150]"},
     ],
     "solution": "import numpy as np\n\ndef raise_salary(salary, amount):\n    return (np.array(salary) + amount).tolist()"},
    {"topic": "배열 연산", "difficulty": "보통", "needs": ["numpy"],
     "prompt": "2차원 리스트(행렬)의 모든 요소 합을 정수로 반환하는 함수 total_sum(m)을 작성하세요. (np.sum 활용)",
     "starter": "import numpy as np\n\ndef total_sum(m):\n    # int() 로 감싸 파이썬 정수로 반환\n    ",
     "tests": [
         {"call": "total_sum([[1, 2], [3, 4]])", "expected": "10"},
         {"call": "total_sum([[5]])", "expected": "5"},
     ],
     "solution": "import numpy as np\n\ndef total_sum(m):\n    return int(np.sum(np.array(m)))"},
    {"topic": "논리 인덱싱", "difficulty": "어려움", "needs": ["numpy"],
     "prompt": "정수 리스트에서 논리 인덱싱으로 짝수만 골라 리스트로 반환하는 함수 evens(nums)를 작성하세요.",
     "starter": "import numpy as np\n\ndef evens(nums):\n    arr = np.array(nums)\n    # arr[조건] 형태의 논리 인덱싱\n    ",
     "tests": [
         {"call": "evens([1, 2, 3, 4])", "expected": "[2, 4]"},
         {"call": "evens([5, 7, 9])", "expected": "[]"},
         {"call": "evens([2, 4, 6])", "expected": "[2, 4, 6]"},
     ],
     "solution": "import numpy as np\n\ndef evens(nums):\n    arr = np.array(nums)\n    return arr[arr % 2 == 0].tolist()"},
    {"topic": "논리 인덱싱", "difficulty": "어려움", "needs": ["numpy"],
     "prompt": "리스트에서 limit보다 큰 값만 골라 리스트로 반환하는 함수 over(nums, limit)를 작성하세요. (논리 인덱싱)",
     "starter": "import numpy as np\n\ndef over(nums, limit):\n    # ages[ages > 20] 을 떠올려 보세요\n    ",
     "tests": [
         {"call": "over([18, 25, 30, 15], 20)", "expected": "[25, 30]"},
         {"call": "over([1, 2], 10)", "expected": "[]"},
     ],
     "solution": "import numpy as np\n\ndef over(nums, limit):\n    arr = np.array(nums)\n    return arr[arr > limit].tolist()"},
    {"topic": "배열 생성 함수", "difficulty": "보통", "needs": ["numpy"],
     "prompt": "start부터 stop 직전까지 step 간격의 정수 리스트를 반환하는 함수 make_range(start, stop, step)를 작성하세요. (np.arange)",
     "starter": "import numpy as np\n\ndef make_range(start, stop, step):\n    # arange 결과를 tolist() 로\n    ",
     "tests": [
         {"call": "make_range(2, 10, 3)", "expected": "[2, 5, 8]"},
         {"call": "make_range(0, 5, 1)", "expected": "[0, 1, 2, 3, 4]"},
     ],
     "solution": "import numpy as np\n\ndef make_range(start, stop, step):\n    return np.arange(start, stop, step).tolist()"},
    {"topic": "배열 생성 함수", "difficulty": "보통", "needs": ["numpy"],
     "prompt": "a부터 b까지 균일한 간격의 수 n개 리스트를 반환하는 함수 make_linspace(a, b, n)를 작성하세요.",
     "starter": "import numpy as np\n\ndef make_linspace(a, b, n):\n    # linspace(시작, 끝, 개수)\n    ",
     "tests": [
         {"call": "make_linspace(0, 10, 5)", "expected": "[0.0, 2.5, 5.0, 7.5, 10.0]"},
         {"call": "make_linspace(0, 1, 2)", "expected": "[0.0, 1.0]"},
     ],
     "solution": "import numpy as np\n\ndef make_linspace(a, b, n):\n    return np.linspace(a, b, n).tolist()"},
    {"topic": "배열 생성 함수", "difficulty": "어려움", "needs": ["numpy"],
     "prompt": "1차원 리스트를 rows행 cols열의 2차원 리스트로 바꾸는 함수 to_matrix(nums, rows, cols)를 작성하세요. (reshape)",
     "starter": "import numpy as np\n\ndef to_matrix(nums, rows, cols):\n    # reshape(rows, cols) 후 tolist()\n    ",
     "tests": [
         {"call": "to_matrix([1, 2, 3, 4, 5, 6], 2, 3)", "expected": "[[1, 2, 3], [4, 5, 6]]"},
         {"call": "to_matrix([1, 2, 3, 4], 2, 2)", "expected": "[[1, 2], [3, 4]]"},
     ],
     "solution": "import numpy as np\n\ndef to_matrix(nums, rows, cols):\n    return np.array(nums).reshape(rows, cols).tolist()"},
    {"topic": "배열 생성 함수", "difficulty": "보통", "needs": ["numpy"],
     "prompt": "2차원 리스트를 1차원 리스트로 펴는 함수 flatten_matrix(m)를 작성하세요. (flatten)",
     "starter": "import numpy as np\n\ndef flatten_matrix(m):\n    # 평탄화 함수 flatten()\n    ",
     "tests": [
         {"call": "flatten_matrix([[1, 2], [3, 4]])", "expected": "[1, 2, 3, 4]"},
         {"call": "flatten_matrix([[7]])", "expected": "[7]"},
     ],
     "solution": "import numpy as np\n\ndef flatten_matrix(m):\n    return np.array(m).flatten().tolist()"},
    {"topic": "2차원 배열", "difficulty": "어려움", "needs": ["numpy"],
     "prompt": "2차원 리스트(행렬)에서 i번째 열을 리스트로 반환하는 함수 col_of(m, i)를 작성하세요. ([:, i] 슬라이싱)",
     "starter": "import numpy as np\n\ndef col_of(m, i):\n    arr = np.array(m)\n    # 모든 행(:)의 i번째 열\n    ",
     "tests": [
         {"call": "col_of([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 2)", "expected": "[3, 6, 9]"},
         {"call": "col_of([[1, 2], [3, 4]], 0)", "expected": "[1, 3]"},
     ],
     "solution": "import numpy as np\n\ndef col_of(m, i):\n    arr = np.array(m)\n    return arr[:, i].tolist()"},
    {"topic": "난수와 통계", "difficulty": "보통", "needs": ["numpy"],
     "prompt": "리스트의 평균을 float로 반환하는 함수 mean_of(nums)를 작성하세요. (np.mean)",
     "starter": "import numpy as np\n\ndef mean_of(nums):\n    # float() 로 감싸 반환\n    ",
     "tests": [
         {"call": "mean_of([2, 4])", "expected": "3.0"},
         {"call": "mean_of([10, 20, 30])", "expected": "20.0"},
     ],
     "solution": "import numpy as np\n\ndef mean_of(nums):\n    return float(np.mean(np.array(nums)))"},
    {"topic": "난수와 통계", "difficulty": "어려움", "needs": ["numpy"],
     "prompt": "리스트를 받아 (평균, 최댓값) 튜플을 반환하는 함수 stats(nums)를 작성하세요. 평균은 float, 최댓값은 int로요.",
     "starter": "import numpy as np\n\ndef stats(nums):\n    # float(), int() 로 파이썬 기본형으로 변환\n    ",
     "tests": [
         {"call": "stats([1, 2, 3])", "expected": "(2.0, 3)"},
         {"call": "stats([10, 20, 30, 40])", "expected": "(25.0, 40)"},
     ],
     "solution": "import numpy as np\n\ndef stats(nums):\n    arr = np.array(nums)\n    return float(np.mean(arr)), int(np.max(arr))"},
    {"topic": "난수와 통계", "difficulty": "어려움", "needs": ["numpy"],
     "prompt": "평균 m, 표준편차 s인 정규분포 난수 n개를 만들어 그 개수를 반환하는 함수 make_heights(m, s, n)를 작성하세요. (np.random.normal)",
     "starter": "import numpy as np\n\ndef make_heights(m, s, n):\n    # normal(평균, 표준편차, 개수) → len()\n    ",
     "tests": [
         {"call": "make_heights(175, 10, 100)", "expected": "100"},
         {"call": "make_heights(0, 1, 5)", "expected": "5"},
     ],
     "solution": "import numpy as np\n\ndef make_heights(m, s, n):\n    data = np.random.normal(m, s, n)\n    return len(data)"},
],
}
