"""
quiz_bank.py — 강의자료 기반 파이썬 연습문제 은행.

섹터(주제) 구성은 숏폼 영상 코스와 동일하다.
  · 파이썬 입문  ← input/lecture.pdf
        파이썬 시작하기 / 변수 / 자료형 / 연산자 / 모듈
  · 파이썬 중급  ← input/intermediate.pdf
        조건문 / 반복문 / 리스트와 튜플 / 딕셔너리와 집합

형식: q(질문) / code(선택, 코드 블록) / options(보기 4개)
      / answer(정답 인덱스) / explain(해설) / difficulty(쉬움|보통|어려움)
"""
from __future__ import annotations
from typing import Dict, List

QUESTION_BANK: Dict[str, Dict[str, List[dict]]] = {

# ═══════════════════ 파이썬 입문 ═══════════════════
"파이썬 입문": {

"파이썬 시작하기": [
    {"q": "파이썬 대화식 모드에서 명령을 입력받는 프롬프트 표시는?",
     "options": [">>>", "$", "#", "py>"],
     "answer": 0,
     "explain": "파이썬 인터프리터를 실행하면 >>> 프롬프트가 나타나고, 여기에 명령을 입력하고 엔터를 치면 바로 실행됩니다.",
     "difficulty": "쉬움"},
    {"q": "명령어들을 모아 파일로 저장해 두고 실행하는 방식을 무엇이라 할까요?",
     "options": ["대화식 모드", "스크립트 모드", "프롬프트 모드", "컴파일 모드"],
     "answer": 1,
     "explain": "스크립트 모드는 파이썬 명령을 소스 코드 파일로 저장해 실행하는 방식입니다. 대화식 모드는 >>> 프롬프트에서 한 줄씩 실행합니다.",
     "difficulty": "쉬움"},
    {"q": "파이썬 소스 코드 파일의 확장자는?",
     "options": [".py", ".python", ".txt", ".code"],
     "answer": 0,
     "explain": "파이썬 소스 코드는 .py 확장자로 저장합니다. 예: hello.py",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "print('Hello Python!!')",
     "options": ["Hello Python!!", "'Hello Python!!'", "print('Hello Python!!')", "오류 발생"],
     "answer": 0,
     "explain": "print()는 따옴표 안의 문자열만 출력합니다. 따옴표 자체는 출력되지 않습니다.",
     "difficulty": "쉬움"},
    {"q": "대화식 모드에서 2 + 3 을 입력하고 엔터를 치면?",
     "options": ["5가 바로 출력된다", "아무 일도 일어나지 않는다", "print를 써야만 출력된다", "오류가 발생한다"],
     "answer": 0,
     "explain": "대화식 모드에서는 입력한 식의 결과가 바로 다음 줄에 출력됩니다. 한 줄씩 즉시 실행되는 것이 대화식 모드의 특징입니다.",
     "difficulty": "쉬움"},
    {"q": "대화식 모드의 단점으로 강의에서 설명한 것은?",
     "options": ["실행 속도가 느리다", "잘못 입력하면 수정이 힘들고 같은 일을 다시 시키기 어렵다", "print() 함수를 쓸 수 없다", "변수를 만들 수 없다"],
     "answer": 1,
     "explain": "대화식 모드는 간단하지만 잘못 입력한 경우 수정이 힘들고 재실행이 어렵습니다. 그래서 명령을 소스 코드 파일로 저장하는 스크립트 모드를 사용합니다.",
     "difficulty": "보통"},
    {"q": "파이썬 인터프리터를 실행하면 화면 첫 줄에 보여주는 것은?",
     "options": ["버전(version) 등의 정보", "예제 코드", "도움말 전체", "지난 작업 기록"],
     "answer": 0,
     "explain": "인터프리터는 처음 자신을 소개합니다. 첫 줄에 버전 등의 정보를 보여주고, 다음 줄에 더 많은 정보를 원할 때 입력할 수 있는 명령들을 보여줍니다.",
     "difficulty": "보통"},
    {"q": "스크립트 파일(xxx.py)에서 변수의 값을 화면에 출력하려면?",
     "code": "weight = 78.2",
     "options": ["weight 라고만 쓰면 된다", "print(weight) 를 사용해야 한다", "show(weight) 를 사용한다", "출력할 방법이 없다"],
     "answer": 1,
     "explain": "대화창 콘솔에서는 변수 이름만 써도 값이 보이지만, 스크립트 파일에서는 반드시 print() 함수를 사용해야 출력됩니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "print('3 + 4')",
     "options": ["7", "3 + 4", "'3 + 4'", "오류 발생"],
     "answer": 1,
     "explain": "따옴표로 감싸면 문자열이므로 계산되지 않고 글자 그대로 3 + 4 가 출력됩니다. 7을 얻으려면 print(3 + 4) 라고 써야 합니다.",
     "difficulty": "보통"},
    {"q": "한 줄씩 입력할 때마다 번역기가 즉시 실행하는 방식은?",
     "options": ["대화식 모드", "스크립트 모드", "배치 모드", "디버그 모드"],
     "answer": 0,
     "explain": "대화식 모드는 >>> 프롬프트에서 명령을 입력하고 엔터를 치면 한 줄 또는 그 이상의 코드를 즉시 실행합니다.",
     "difficulty": "쉬움"},
],

"변수": [
    {"q": "강의에서 설명한 변수의 정의로 옳은 것은?",
     "options": ["컴퓨터의 메모리 공간에 이름을 붙인 것", "항상 숫자만 저장하는 공간", "한 번 정하면 바꿀 수 없는 값", "파이썬 예약어의 일종"],
     "answer": 0,
     "explain": "변수는 메모리 공간에 이름을 붙인 것으로, 정수·실수·문자열 등의 자료값을 저장할 수 있고 이름을 적어 다시 꺼낼 수 있습니다.",
     "difficulty": "쉬움"},
    {"q": "변수 할당문 weight = 78.2 에서 = 기호의 의미는?",
     "options": ["왼쪽과 오른쪽이 같다", "오른쪽 값을 왼쪽 변수에 저장하라", "두 값을 비교하라", "왼쪽 값을 오른쪽으로 복사하라"],
     "answer": 1,
     "explain": "= 는 '같다'는 등호가 아니라 오른쪽 값을 왼쪽 변수에 저장하라는 할당(대입) 연산자입니다.",
     "difficulty": "쉬움"},
    {"q": "'변수(변하는 수)'라는 이름이 붙은 이유는?",
     "options": ["저장된 값이 수시로 바뀔 수 있어서", "변신하는 함수라서", "수학의 미지수와 같아서", "숫자만 저장할 수 있어서"],
     "answer": 0,
     "explain": "변수에 저장된 값은 수시로 바뀔 수 있어 '변하는 수'라고 명명되었습니다. 이때 '수'는 수치값이 아니라 데이터로 이해해야 합니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드 실행 후 weight의 값은?",
     "code": "weight = 78.2\nweight = 76.9",
     "options": ["78.2", "76.9", "155.1", "오류 발생"],
     "answer": 1,
     "explain": "변수의 값은 언제든지 바꿀 수 있습니다. 다이어트로 체중이 줄듯 나중에 할당한 76.9가 저장됩니다.",
     "difficulty": "쉬움"},
    {"q": "다음 동시 할당문 실행 후 출력 결과는?",
     "code": "x, y = 100, 200\nprint(x, y)",
     "options": ["100 200", "200 100", "(100, 200)", "오류 발생"],
     "answer": 0,
     "explain": "한 줄에 여러 변수를 선언하고 동시에 값을 할당하는 동시할당문입니다. x에 100, y에 200이 순서대로 저장됩니다.",
     "difficulty": "보통"},
    {"q": "대화창 콘솔에서 x, y 처럼 쉼표로 두 변수를 입력하면 어떻게 출력될까요?",
     "code": "x = 100\ny = 200",
     "options": ["(100, 200) 묶음 형태", "100 200", "x y", "오류 발생"],
     "answer": 0,
     "explain": "한 행에 쉼표로 변수들을 쓰면 (100, 200) 형태의 묶음으로 출력됩니다.",
     "difficulty": "어려움"},
    {"q": "다음 중 변수 이름으로 사용할 수 없는 것은?",
     "options": ["weight", "if", "my_height", "score2"],
     "answer": 1,
     "explain": "if 는 파이썬이 내부적으로 사용하는 예약어라 변수 이름으로 쓰면 오류가 발생합니다.",
     "difficulty": "보통"},
    {"q": "변수 이름 규칙으로 옳지 않은 것은?",
     "options": ["숫자로 시작할 수 있다", "예약어는 사용할 수 없다", "변수 이름은 식별자의 일종이다", "역할을 설명하는 이름이 좋다"],
     "answer": 0,
     "explain": "변수 이름은 숫자로 시작할 수 없습니다. 2nd_place 같은 이름은 문법 오류입니다.",
     "difficulty": "보통"},
    {"q": "강의에서 권장하는 좋은 변수 이름 짓기는?",
     "options": ["가능한 한 짧게 x1, x2 로 짓는다", "변수의 역할을 잘 설명하는 이름(weight, height)을 짓는다", "모두 대문자로 짓는다", "아무 글자나 무작위로 짓는다"],
     "answer": 1,
     "explain": "체중과 키를 x1, x2라고 하는 것보다 weight, height라고 하는 편이 이해하기 쉽습니다.",
     "difficulty": "쉬움"},
    {"q": "식별자(identifier)의 역할은?",
     "options": ["변수들을 서로 구별한다", "변수의 값을 두 배로 만든다", "코드 실행 속도를 높인다", "자료형을 바꾼다"],
     "answer": 0,
     "explain": "사람 이름이 사람을 구별하듯 식별자는 변수들을 구별하는 역할을 합니다.",
     "difficulty": "보통"},
    {"q": "문자열을 만들 때 사용하는 기호는?",
     "options": ["큰따옴표(\")나 작은따옴표(')", "대괄호 [ ]", "중괄호 { }", "슬래시 / /"],
     "answer": 0,
     "explain": "문자열은 큰따옴표나 작은따옴표로 만들 수 있습니다. 파이썬에서는 이런 문자열 데이터를 '객체'라고 표현합니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "s1 = 'Hello'\nprint(len(s1))",
     "options": ["4", "5", "Hello", "오류 발생"],
     "answer": 1,
     "explain": "len() 함수는 문자열의 길이를 돌려줍니다. 'Hello'는 5글자입니다. 이렇게 미리 정의된 기능을 함수(function)라고 합니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "name = '파이썬'\nname = name + '3'\nprint(name)",
     "options": ["파이썬", "파이썬3", "name3", "오류 발생"],
     "answer": 1,
     "explain": "두 문자열을 합치려면 + 연산을 사용합니다. '파이썬' 뒤에 '3'이 붙어 '파이썬3'이 출력됩니다.",
     "difficulty": "보통"},
    {"q": "다음 코드 실행 후 b의 값은?",
     "code": "a = 10\nb = a\na = 20",
     "options": ["10", "20", "30", "오류 발생"],
     "answer": 0,
     "explain": "b = a 시점에 a의 값 10이 b에 저장됩니다. 그 뒤 a를 20으로 바꿔도 b는 그대로 10입니다.",
     "difficulty": "어려움"},
],

"자료형": [
    {"q": "강의에서 배운 파이썬의 가장 단순한 자료형 4가지가 아닌 것은?",
     "options": ["정수(int)", "실수(float)", "리스트(list)", "부울(bool)"],
     "answer": 2,
     "explain": "기본 자료형 4가지는 정수, 실수, 문자열, 부울입니다. 리스트는 여러 데이터를 묶는 자료형으로 중급에서 배웁니다.",
     "difficulty": "쉬움"},
    {"q": "변수의 자료형을 알아내는 함수는?",
     "options": ["len()", "type()", "print()", "int()"],
     "answer": 1,
     "explain": "type() 함수에 변수 이름을 넣으면 그 변수의 자료형을 알려줍니다.",
     "difficulty": "쉬움"},
    {"q": "type(3.14) 의 결과는?",
     "options": ["int", "float", "str", "bool"],
     "answer": 1,
     "explain": "3.14처럼 소수점이 있는 수는 실수이고, 파이썬에서 실수 타입은 float입니다.",
     "difficulty": "쉬움"},
    {"q": "type(10) 의 결과는?",
     "options": ["int", "float", "str", "number"],
     "answer": 0,
     "explain": "10처럼 소수점이 없는 숫자는 정수(integer), 즉 int입니다.",
     "difficulty": "쉬움"},
    {"q": "type('10') 의 결과는?",
     "options": ["int", "float", "str", "bool"],
     "answer": 2,
     "explain": "따옴표로 감싼 '10'은 숫자가 아니라 문자열(str)입니다. 따옴표가 있으면 문자열, 없으면 숫자입니다.",
     "difficulty": "보통"},
    {"q": "강의의 주의사항에 따르면, 파이썬에서 문자열과 숫자를 구분하는 기준은?",
     "options": ["글자 수", "따옴표의 유무", "대문자 여부", "변수 이름"],
     "answer": 1,
     "explain": "따옴표가 있으면 문자열이고 따옴표가 없으면 숫자입니다.",
     "difficulty": "쉬움"},
    {"q": "다음 두 코드의 결과로 옳은 것은?",
     "code": "x, y = 10, 10\nprint(x + y)\n\na, b = 'good', 'morning'\nprint(a + b)",
     "options": ["20 / goodmorning", "20 / 오류 발생", "1010 / goodmorning", "20 / good morning"],
     "answer": 0,
     "explain": "자료형에 따라 + 연산의 의미가 달라집니다. 정수면 덧셈(20), 문자열이면 이어붙이기(goodmorning)입니다. 이것이 자료형을 신경 써야 하는 이유입니다.",
     "difficulty": "보통"},
    {"q": "참(True)과 거짓(False)을 나타내는 자료형은?",
     "options": ["bool", "int", "str", "binary"],
     "answer": 0,
     "explain": "부울(bool)형은 참이나 거짓을 나타내며, True와 False 두 가지 값만 가집니다.",
     "difficulty": "쉬움"},
    {"q": "부울(bool)형이 특히 유용하게 쓰이는 곳은?",
     "options": ["문자열 길이 계산", "조건문이나 반복문에서 조건 검사", "소수점 계산", "파일 저장"],
     "answer": 1,
     "explain": "부울형은 조건문이나 반복문에서 어떤 조건을 검사할 때 유용합니다.",
     "difficulty": "쉬움"},
    {"q": "int('7') + 3 의 결과는?",
     "options": ["73", "10", "'73'", "오류 발생"],
     "answer": 1,
     "explain": "int()는 문자열 '7'을 정수 7로 변환합니다. 7 + 3 = 10이 됩니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "print(str(1) + str(2))",
     "options": ["3", "12", "1 2", "오류 발생"],
     "answer": 1,
     "explain": "str()로 변환된 '1'과 '2'는 문자열이므로 + 는 이어붙이기가 되어 12가 출력됩니다.",
     "difficulty": "어려움"},
    {"q": "3 과 3.0 에 대한 설명으로 옳은 것은?",
     "options": ["완전히 같은 값이고 자료형도 같다", "값은 같아 보여도 자료형이 다르다(int와 float)", "3.0은 문자열이다", "3은 실수다"],
     "answer": 1,
     "explain": "3은 정수(int), 3.0은 실수(float)입니다. 소수점이 붙으면 실수가 됩니다.",
     "difficulty": "보통"},
],

"연산자": [
    {"q": "파이썬에서 나눗셈 연산 / 의 결과는 항상?",
     "code": "print(10 / 5)",
     "options": ["정수로 계산된다 (2)", "실수로 계산된다 (2.0)", "문자열이 된다", "반올림된다"],
     "answer": 1,
     "explain": "파이썬에서 / 는 항상 실수로 계산합니다. 10 / 5 도 2가 아니라 2.0입니다. 몫을 정수로 얻으려면 // 를 씁니다.",
     "difficulty": "보통"},
    {"q": "7 // 2 의 결과는?",
     "options": ["3.5", "3", "4", "1"],
     "answer": 1,
     "explain": "// 는 몫 연산자입니다. 소수점 이하는 없어지고 정수 부분 3만 남습니다.",
     "difficulty": "쉬움"},
    {"q": "7 % 2 의 결과는?",
     "options": ["3", "3.5", "1", "0"],
     "answer": 2,
     "explain": "% 는 나머지 연산자입니다. x % y 는 x를 y로 나누어서 남은 나머지를 반환합니다. 7 ÷ 2 = 몫 3, 나머지 1입니다.",
     "difficulty": "쉬움"},
    {"q": "10 % 3 의 결과는?",
     "options": ["3", "1", "0", "3.33"],
     "answer": 1,
     "explain": "10을 3으로 나누면 몫이 3이고 나머지가 1입니다.",
     "difficulty": "쉬움"},
    {"q": "2의 7제곱을 계산하는 파이썬 수식은?",
     "options": ["2 ^ 7", "2 ** 7", "2 * 7", "pow 2 7"],
     "answer": 1,
     "explain": "거듭제곱은 ** 연산자를 씁니다. 2가 밑(base), 7이 지수(exponent)입니다.",
     "difficulty": "쉬움"},
    {"q": "수식 7 + 4 에서 7과 4를 부르는 말은?",
     "options": ["연산자", "피연산자", "식별자", "예약어"],
     "answer": 1,
     "explain": "연산의 대상이 되는 숫자나 변수를 피연산자(operand), 연산을 나타내는 기호(+)를 연산자(operator)라고 합니다.",
     "difficulty": "보통"},
    {"q": "다음 복합 할당 연산 후 x의 값은?",
     "code": "x = 10\nx += 5\nx *= 2",
     "options": ["20", "25", "30", "15"],
     "answer": 2,
     "explain": "복합 할당 연산자는 산술 연산과 할당을 결합한 것입니다. x += 5 로 15, x *= 2 로 30이 됩니다.",
     "difficulty": "보통"},
    {"q": "복합 할당 연산자 x @= y 의 의미는? (@는 임의의 산술 연산자)",
     "options": ["x = x @ y", "y = x @ y", "x == y", "x와 y를 맞바꾼다"],
     "answer": 0,
     "explain": "산술 연산자와 할당 연산자를 결합한 표현입니다. 예를 들어 x += 5 는 x = x + 5 와 같습니다.",
     "difficulty": "어려움"},
    {"q": "= 와 == 의 차이로 옳은 것은?",
     "options": ["= 는 할당, == 는 비교", "= 는 비교, == 는 할당", "둘 다 비교", "둘 다 할당"],
     "answer": 0,
     "explain": "= 는 값을 변수에 저장하는 할당 연산자, == 는 두 값이 같은지 검사해 True/False를 돌려주는 비교 연산자입니다.",
     "difficulty": "보통"},
    {"q": "비교 연산자(>, <, == 등)의 연산 결과는?",
     "options": ["정수", "True 또는 False", "문자열", "실수"],
     "answer": 1,
     "explain": "비교 연산은 그 결과로 부울 값인 True 혹은 False를 반환합니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드에서 오류가 발생하는 이유는?",
     "code": "7 = x",
     "options": ["x가 정의되지 않아서", "= 의 왼쪽이 변수가 아니어서", "7이 너무 작아서", "오류가 발생하지 않는다"],
     "answer": 1,
     "explain": "= 연산자의 왼쪽은 반드시 값을 저장할 수 있는 변수여야 합니다. 숫자 7에는 값을 저장할 수 없습니다.",
     "difficulty": "보통"},
    {"q": "2 + 3 * 4 의 결과는?",
     "options": ["20", "14", "24", "9"],
     "answer": 1,
     "explain": "곱셈이 덧셈보다 우선순위가 높아 3 * 4 가 먼저 계산됩니다.",
     "difficulty": "보통"},
    {"q": "(2 + 3) * 4 의 결과는?",
     "options": ["14", "20", "24", "11"],
     "answer": 1,
     "explain": "우선순위와 다른 순서로 계산하고 싶을 때는 수학처럼 괄호를 사용합니다. 괄호 안이 먼저 계산되어 5 * 4 = 20입니다.",
     "difficulty": "쉬움"},
    {"q": "2 * 3 ** 2 의 결과는?",
     "options": ["36", "18", "12", "64"],
     "answer": 1,
     "explain": "거듭제곱 연산자(**)는 다른 연산자들보다 높은 우선순위를 가집니다. 3 ** 2 = 9가 먼저 계산되어 2 * 9 = 18입니다.",
     "difficulty": "어려움"},
    {"q": "다음 논리 연산의 결과는?",
     "code": "print(True and False)\nprint(True or False)\nprint(not True)",
     "options": ["False True False", "True False True", "False False False", "True True False"],
     "answer": 0,
     "explain": "and는 둘 다 참일 때만 True, or는 하나라도 참이면 True, not은 반대 값을 돌려줍니다.",
     "difficulty": "어려움"},
    {"q": "다음 중 결과가 True 인 식은?",
     "options": ["3 > 5 or 2 < 1", "not (1 == 1)", "3 >= 3 and 2 != 1", "5 < 3"],
     "answer": 2,
     "explain": "3 >= 3 은 True, 2 != 1 도 True이므로 and 결과도 True입니다. 나머지는 모두 False입니다.",
     "difficulty": "보통"},
],

"모듈": [
    {"q": "random 모듈을 사용하기 위해 가장 먼저 해야 하는 것은?",
     "options": ["pip install random", "import random", "include random", "new random"],
     "answer": 1,
     "explain": "random은 파이썬 표준 라이브러리라 설치 없이 import random 한 줄로 바로 사용할 수 있습니다.",
     "difficulty": "쉬움"},
    {"q": "다음 중 설치 없이 바로 쓸 수 있는 파이썬 내장 함수가 아닌 것은?",
     "options": ["print()", "len()", "input()", "sqrt()"],
     "answer": 3,
     "explain": "print, input, len, sum, min, max, int, str 등 70여 가지는 내장 함수입니다. sqrt()는 math 모듈을 import 해야 쓸 수 있습니다.",
     "difficulty": "보통"},
    {"q": "강의에서 배운 random 모듈의 역할은?",
     "options": ["수학 상수 제공", "임의의 수 생성, 요소 무작위 섞기·선택", "문자열 처리", "파일 입출력"],
     "answer": 1,
     "explain": "random 모듈은 임의의 수를 생성하거나, 리스트나 튜플 내의 요소를 무작위로 섞거나 선택하는 함수를 포함합니다.",
     "difficulty": "쉬움"},
    {"q": "1부터 6까지 정수 중 하나를 무작위로 뽑는 코드는?",
     "code": "import random",
     "options": ["random.random(1, 6)", "random.randint(1, 6)", "random.choice(1, 6)", "random.range(1, 6)"],
     "answer": 1,
     "explain": "randint(a, b)는 a 이상 b 이하의 정수를 무작위로 돌려줍니다. 양 끝이 모두 포함됩니다.",
     "difficulty": "보통"},
    {"q": "random.choice(['가', '나', '다']) 가 하는 일은?",
     "options": ["리스트를 섞는다", "리스트에서 하나를 무작위로 고른다", "리스트를 정렬한다", "리스트 길이를 구한다"],
     "answer": 1,
     "explain": "choice()는 시퀀스에서 항목 하나를 무작위로 골라 돌려줍니다. 섞는 것은 shuffle()입니다.",
     "difficulty": "보통"},
    {"q": "math 모듈에 포함된 것이 아닌 것은?",
     "options": ["원주율 pi", "floor() 내림 함수", "randint() 무작위 정수", "sin() 삼각함수"],
     "answer": 2,
     "explain": "math 모듈은 원주율, 자연상수, fabs(), ceil(), floor(), log(), sin(), cos() 등을 포함합니다. randint()는 random 모듈입니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "import math\nprint(math.sqrt(16))",
     "options": ["4", "4.0", "8.0", "256"],
     "answer": 1,
     "explain": "sqrt는 제곱근을 구하며 결과는 항상 실수(float)입니다. 16의 제곱근은 4.0입니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "import math\nprint(math.floor(3.7), math.ceil(3.2))",
     "options": ["3 4", "4 3", "3 3", "4 4"],
     "answer": 0,
     "explain": "floor는 내림(3.7 → 3), ceil은 올림(3.2 → 4)입니다.",
     "difficulty": "어려움"},
    {"q": "표준 라이브러리에 대한 설명으로 옳은 것은?",
     "options": ["파이썬과 함께 제공되어 import만 하면 쓸 수 있는 모듈 모음", "반드시 돈을 내고 사야 하는 라이브러리", "다른 언어로만 작성된 코드", "인터넷 연결이 필요한 기능"],
     "answer": 0,
     "explain": "파이썬은 터틀 그래픽, random, math 등 다양한 모듈을 표준 라이브러리라는 이름으로 기본 제공합니다.",
     "difficulty": "쉬움"},
    {"q": "모듈을 가져올 때 사용하는 키워드는?",
     "options": ["import", "include", "require", "using"],
     "answer": 0,
     "explain": "파이썬은 import 키워드로 모듈을 가져옵니다. 예: import random, import math",
     "difficulty": "쉬움"},
],
},

# ═══════════════════ 파이썬 중급 ═══════════════════
"파이썬 중급": {

"조건문": [
    {"q": "어떤 조건을 만족하는지 판정하는 식을 무엇이라 할까요?",
     "options": ["조건식", "할당식", "반복식", "출력식"],
     "answer": 0,
     "explain": "조건을 만족하는지 그렇지 않은지를 판정하는 식을 조건식(condition expression)이라 하며, True 또는 False 값을 가집니다.",
     "difficulty": "쉬움"},
    {"q": "조건식 100 > 1 이 생성하는 값은?",
     "options": ["1", "True", "100", "\"참\""],
     "answer": 1,
     "explain": "100이 1보다 크므로 이 관계식은 참을 의미하는 값 True를 생성합니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "score = 75\nif score >= 60:\n    print('합격입니다')\nelse:\n    print('불합격입니다')",
     "options": ["합격입니다", "불합격입니다", "둘 다 출력", "아무것도 출력 안 됨"],
     "answer": 0,
     "explain": "75는 60 이상이므로 조건이 참이 되어 '합격입니다'가 출력됩니다. if-else는 \"조건이 참이면 이것, 아니면 저것\"입니다.",
     "difficulty": "쉬움"},
    {"q": "조건식 뒤에 붙는 콜론(:)의 역할로 강의에서 설명한 것은?",
     "options": ["문장이 끝났다는 표시", "다음에 이 문장에 딸린 코드 블록이 나타난다는 표시", "주석의 시작", "출력 명령"],
     "answer": 1,
     "explain": "콜론은 \"아직 문장이 끝나지 않았고, 다음에 이 문장에 딸린 코드 블록이 나타난다\"고 인터프리터에게 알리는 기호입니다.",
     "difficulty": "보통"},
    {"q": "if 문에서 여러 문장을 하나의 블록으로 묶는 방법은?",
     "options": ["중괄호 { }로 감싼다", "동일한 개수의 공백으로 들여쓰기한다", "세미콜론으로 연결한다", "괄호 ( )로 감싼다"],
     "answer": 1,
     "explain": "파이썬의 블록은 들여쓰기로 완성됩니다. 같은 블록의 문장들은 동일한 개수의 공백으로 들여 써야 합니다.",
     "difficulty": "쉬움"},
    {"q": "if 문에서 들여쓰기를 하지 않으면 어떻게 될까요?",
     "code": "if x > 1:\nprint('큽니다')",
     "options": ["정상 동작한다", "오류가 발생한다", "조건과 상관없이 출력된다", "자동으로 들여쓰기된다"],
     "answer": 1,
     "explain": "if 문에 딸린 블록은 반드시 들여쓰기해야 합니다. 들여쓰기가 없으면 문법 오류(IndentationError)가 발생합니다.",
     "difficulty": "보통"},
    {"q": "elif 키워드의 의미는?",
     "options": ["else if 를 합친 것", "end if 를 합친 것", "else 의 줄임말", "error if 를 합친 것"],
     "answer": 0,
     "explain": "elif는 \"else if\"를 합친 것으로, 앞의 조건이 거짓일 때 다른 조건을 추가로 검사합니다.",
     "difficulty": "쉬움"},
    {"q": "if 문에서 조건이 거짓일 때 실행되는 부분을 만드는 키워드는?",
     "options": ["elif", "else", "not", "except"],
     "answer": 1,
     "explain": "else 는 위의 조건이 거짓일 때 실행됩니다. elif 는 새로운 조건을 추가로 검사할 때 씁니다.",
     "difficulty": "쉬움"},
    {"q": "다음 if-elif-else 코드의 출력 결과는?",
     "code": "num = 0\nif num > 0:\n    print('양수입니다')\nelif num == 0:\n    print('0입니다')\nelse:\n    print('음수입니다')",
     "options": ["양수입니다", "0입니다", "음수입니다", "아무것도 출력 안 됨"],
     "answer": 1,
     "explain": "첫 조건(num > 0)은 거짓이고 elif의 num == 0 이 참이므로 '0입니다'가 출력됩니다.",
     "difficulty": "보통"},
    {"q": "if-elif-else에서 위의 조건이 참이면 아래 조건들은?",
     "options": ["전부 차례로 검사한다", "검사하지 않고 건너뛴다", "마지막 것만 검사한다", "오류가 발생한다"],
     "answer": 1,
     "explain": "하나의 조건이 참이 되어 해당 블록을 실행하면 나머지 elif/else는 검사하지 않고 건너뜁니다.",
     "difficulty": "보통"},
    {"q": "24시 체계 시간으로 오전/오후를 나누는 코드의 출력은?",
     "code": "hour = 15\nif hour < 12:\n    print('오전입니다')\nelse:\n    print('오후입니다')",
     "options": ["오전입니다", "오후입니다", "둘 다 출력", "오류 발생"],
     "answer": 1,
     "explain": "15는 12보다 작지 않으므로 else의 '오후입니다'가 출력됩니다. 오전이면서 동시에 오후일 수 없는 배타적 조건입니다.",
     "difficulty": "쉬움"},
    {"q": "사용자에게 받은 자연수가 짝수인지 검사하는 조건식은?",
     "code": "num = int(input())",
     "options": ["num % 2 == 0", "num // 2 == 0", "num / 2 == 0", "num == 2"],
     "answer": 0,
     "explain": "2로 나눈 나머지(%)가 0이면 짝수입니다. 몫(//)이나 나눗셈(/)으로는 짝수 여부를 판단할 수 없습니다.",
     "difficulty": "보통"},
    {"q": "다음 중첩(내부) if 코드의 출력 결과는?",
     "code": "num = 0\nif num >= 0:\n    if num == 0:\n        print('0입니다')\n    else:\n        print('양수입니다')\nelse:\n    print('음수입니다')",
     "options": ["0입니다", "양수입니다", "음수입니다", "오류 발생"],
     "answer": 0,
     "explain": "num=0은 0 이상이므로 내부 if 블록으로 들어가고, num == 0 이 참이라 '0입니다'가 출력됩니다. if 안에 또 if를 두는 것을 내부(중첩) if 블록이라 합니다.",
     "difficulty": "어려움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "x = 0\nif x:\n    print('참')\nelse:\n    print('거짓')",
     "options": ["참", "거짓", "0", "오류 발생"],
     "answer": 1,
     "explain": "숫자 0은 조건문에서 False로 취급됩니다. 그래서 else 쪽의 '거짓'이 출력됩니다.",
     "difficulty": "어려움"},
],

"반복문": [
    {"q": "파이썬의 두 가지 반복 종류를 바르게 짝지은 것은?",
     "options": ["횟수 제어 for / 조건 제어 while", "횟수 제어 while / 조건 제어 for", "둘 다 횟수 제어", "둘 다 조건 제어"],
     "answer": 0,
     "explain": "for 문은 횟수를 정해놓고 반복(횟수 제어), while 문은 조건이 만족되는 동안 반복(조건 제어)합니다.",
     "difficulty": "쉬움"},
    {"q": "반복 횟수를 미리 알고 있을 때 적합한 반복문은?",
     "options": ["for 문", "while 문", "if 문", "break 문"],
     "answer": 0,
     "explain": "횟수 제어 반복(for)은 반복을 시작하기 전에 반복 횟수를 미리 아는 경우에 사용합니다.",
     "difficulty": "쉬움"},
    {"q": "강의에서 설명한 반복문을 쓰는 이유는?",
     "options": ["같은 문장을 복사·붙여넣기하는 것보다 프로그램이 간결해진다", "코드가 더 길어진다", "변수를 안 만들어도 된다", "조건문이 필요 없어진다"],
     "answer": 0,
     "explain": "환영 인사를 100번 출력해야 한다면 복사·붙여넣기보다 반복문이 훨씬 간단하고, 프로그래밍 시간도 단축됩니다.",
     "difficulty": "쉬움"},
    {"q": "range(5) 가 생성하는 숫자 시퀀스는?",
     "options": ["1, 2, 3, 4, 5", "0, 1, 2, 3, 4", "0, 1, 2, 3, 4, 5", "5개의 5"],
     "answer": 1,
     "explain": "range(5)는 0부터 4까지의 숫자 시퀀스를 자동으로 생성합니다. 5는 포함되지 않습니다.",
     "difficulty": "쉬움"},
    {"q": "range(start, stop, step) 의 의미는?",
     "options": ["start부터 stop까지 step 간격", "start부터 (stop-1)까지 step 간격", "stop부터 start까지", "step부터 stop까지"],
     "answer": 1,
     "explain": "range(start, stop, step)은 start에서 시작하여 (stop-1)까지 step 간격으로 정수를 생성합니다.",
     "difficulty": "보통"},
    {"q": "range(2, 10, 3) 이 만드는 숫자들은?",
     "options": ["2, 5, 8", "2, 5, 8, 11", "3, 6, 9", "2, 3, 4, …, 9"],
     "answer": 0,
     "explain": "2부터 시작해 3씩 커지며 10 직전까지 갑니다. 2, 5, 8 다음인 11은 범위를 넘어 제외됩니다.",
     "difficulty": "보통"},
    {"q": "1부터 5까지 반복하고 싶을 때 올바른 range는?",
     "options": ["range(5)", "range(1, 5)", "range(1, 6)", "range(0, 5)"],
     "answer": 2,
     "explain": "range(start, stop)은 start부터 (stop-1)까지 생성합니다. 1~5를 얻으려면 range(1, 6)이어야 합니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "for i in 'abc':\n    print(i, end=' ')",
     "options": ["abc", "a b c", "i i i", "오류 발생"],
     "answer": 1,
     "explain": "for-in은 문자열에도 적용할 수 있습니다. 문자열의 글자를 하나씩 꺼내 a b c 가 출력됩니다.",
     "difficulty": "보통"},
    {"q": "다음 코드는 몇 번 반복될까요?",
     "code": "for x in [10, 20, 30]:\n    print(x)",
     "options": ["3번", "10번", "30번", "60번"],
     "answer": 0,
     "explain": "리스트의 항목 수만큼 반복합니다. [10, 20, 30]은 항목이 3개라 3번 반복됩니다.",
     "difficulty": "쉬움"},
    {"q": "while 루프가 무한 루프가 되는 코드는?",
     "options": ["while True:", "while False:", "while i < 5:", "while 0:"],
     "answer": 0,
     "explain": "조건에 True가 있으면 항상 참이므로 무한히 반복됩니다. 신호등 제어처럼 일부러 쓰기도 하며, 빠져나올 땐 break를 사용합니다.",
     "difficulty": "쉬움"},
    {"q": "while 문의 조건이 처음부터 거짓이면?",
     "code": "i = 10\nwhile i < 5:\n    print(i)",
     "options": ["블록이 한 번도 실행되지 않는다", "한 번은 실행된다", "무한 반복된다", "오류가 발생한다"],
     "answer": 0,
     "explain": "while은 조건이 참인 동안만 반복합니다. 처음부터 거짓이면 블록은 한 번도 실행되지 않습니다.",
     "difficulty": "보통"},
    {"q": "break와 continue의 차이로 옳은 것은?",
     "options": ["break는 루프를 빠져나오고, continue는 아래 문장만 건너뛰고 반복을 계속한다",
                 "break는 건너뛰기, continue는 루프 종료다",
                 "둘 다 루프를 종료한다",
                 "둘 다 한 회차만 건너뛴다"],
     "answer": 0,
     "explain": "break는 가장 가까운 블록(루프)을 즉시 빠져나오고, continue는 그 아래 문장만 건너뛴 채 반복을 계속합니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "for i in range(5):\n    if i == 2:\n        break\n    print(i, end=' ')",
     "options": ["0 1", "0 1 2", "0 1 3 4", "2 3 4"],
     "answer": 0,
     "explain": "i가 2가 되는 순간 break로 루프를 완전히 빠져나오므로 0 1 만 출력됩니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "for i in range(5):\n    if i == 2:\n        continue\n    print(i, end=' ')",
     "options": ["0 1 2 3 4", "0 1 3 4", "0 1", "2"],
     "answer": 1,
     "explain": "i가 2일 때만 continue로 print를 건너뛰므로 2가 빠진 0 1 3 4가 출력됩니다.",
     "difficulty": "어려움"},
    {"q": "다음 while 루프의 출력 결과는?",
     "code": "i = 0\nwhile i < 5:\n    print('환영합니다')\n    i = i + 1",
     "options": ["환영합니다 4번 출력", "환영합니다 5번 출력", "환영합니다 6번 출력", "무한 반복"],
     "answer": 1,
     "explain": "i가 0부터 4까지 다섯 번 조건이 참이므로 5회 반복됩니다. i를 1씩 증가시키므로 무한 루프가 아닙니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "total = 0\ncount = 1\nwhile count <= 10:\n    total += count\n    count += 1\nprint(total)",
     "options": ["10", "45", "55", "100"],
     "answer": 2,
     "explain": "1부터 10까지의 합을 while 루프로 계산하는 코드입니다. 1+2+…+10 = 55입니다.",
     "difficulty": "어려움"},
],

"리스트와 튜플": [
    {"q": "파이썬에서 리스트를 만들 때 사용하는 기호는?",
     "options": ["대괄호 [ ]", "중괄호 { }", "소괄호 ( )", "꺾쇠 < >"],
     "answer": 0,
     "explain": "리스트는 대괄호로 만듭니다. 중괄호는 딕셔너리·집합, 소괄호는 튜플입니다.",
     "difficulty": "쉬움"},
    {"q": "강의에서 리스트가 필요한 이유로 든 상황은?",
     "options": ["사람이 100명이면 변수도 100개 필요해지는 문제", "계산 속도를 높이려고", "들여쓰기를 줄이려고", "문자열을 못 쓰는 문제"],
     "answer": 0,
     "explain": "학생 수만큼 변수를 만들 수는 없습니다. 리스트를 쓰면 하나의 변수에 여러 개의 값을 담을 수 있습니다.",
     "difficulty": "쉬움"},
    {"q": "비어 있는 리스트를 만드는 코드는?",
     "options": ["members = [ ]", "members = { }", "members = ( )", "members = empty"],
     "answer": 0,
     "explain": "초기 항목이 없으면 빈 대괄호로 빈 리스트를 만들 수 있습니다. 나중에 append()로 추가하면 됩니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "fruits = ['사과', '배', '포도']\nprint(fruits[1])",
     "options": ["사과", "배", "포도", "오류 발생"],
     "answer": 1,
     "explain": "리스트의 첫 번째 데이터는 인덱스 0을 가집니다. fruits[1]은 두 번째 항목인 '배'입니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "letters = ['a', 'b', 'c', 'd']\nprint(letters[-1])",
     "options": ["a", "d", "c", "오류 발생"],
     "answer": 1,
     "explain": "인덱스를 음수로 주면 뒤에서부터 셉니다. -1은 리스트 맨 끝의 데이터를 얻을 때 유용합니다.",
     "difficulty": "보통"},
    {"q": "letters[2:5] 슬라이싱이 추출하는 항목은?",
     "options": ["인덱스 2부터 5까지", "인덱스 2부터 4까지", "인덱스 3부터 5까지", "처음 5개"],
     "answer": 1,
     "explain": "슬라이싱은 시작 인덱스부터 (끝-1)까지 추출합니다. 원본은 손상되지 않고 부분 복사본이 새로 만들어집니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "nums = [1, 2, 3, 4, 5]\nprint(nums[1:4])",
     "options": ["[1, 2, 3]", "[2, 3, 4]", "[2, 3, 4, 5]", "[1, 2, 3, 4]"],
     "answer": 1,
     "explain": "[1:4]는 인덱스 1부터 3까지(4 미포함)입니다. 값으로는 2, 3, 4입니다.",
     "difficulty": "보통"},
    {"q": "슬라이싱에서 두 번째 인덱스를 생략하면? (예: letters[2:])",
     "options": ["오류가 발생한다", "리스트의 끝까지라고 가정한다", "한 개만 추출된다", "처음부터라고 가정한다"],
     "answer": 1,
     "explain": "두 번째 인덱스가 생략되면 리스트의 끝까지로 가정합니다. 콜론만 있으면([:]) 처음부터 끝까지입니다.",
     "difficulty": "어려움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "a = [1, 2]\nb = [3, 4]\nprint(a + b)",
     "options": ["[4, 6]", "[1, 2, 3, 4]", "[[1,2],[3,4]]", "오류 발생"],
     "answer": 1,
     "explain": "정수 리스트끼리 더하면 원소끼리 더해지는 게 아니라 리스트가 합쳐집니다. 원소끼리 더하려면 넘파이(NumPy)가 필요합니다.",
     "difficulty": "보통"},
    {"q": "리스트 끝에 항목을 추가하는 메소드는?",
     "options": ["append()", "add()", "push()", "attach()"],
     "answer": 0,
     "explain": "append()는 맨 뒤에 추가하고, 원하는 위치에 끼워 넣을 땐 insert()를 씁니다.",
     "difficulty": "쉬움"},
    {"q": "리스트의 맨 앞(인덱스 0)에 항목을 끼워 넣는 코드는?",
     "code": "members = ['Jin', 'Suga']",
     "options": ["members.insert(0, 'RM')", "members.append('RM')", "members.add(0, 'RM')", "members[0] + 'RM'"],
     "answer": 0,
     "explain": "insert(위치, 값)는 원하는 위치에 항목을 끼워 넣습니다. append()는 항상 맨 뒤에 추가합니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "heights = [165, 178, 172]\nprint(len(heights), max(heights))",
     "options": ["3 178", "3 165", "515 178", "오류 발생"],
     "answer": 0,
     "explain": "len()은 리스트의 길이, max()는 항목 중 최댓값을 반환합니다. min(), sum() 등의 내장 함수도 같은 방식으로 쓸 수 있습니다.",
     "difficulty": "보통"},
    {"q": "리스트 요소의 값을 변경하는 방법은?",
     "code": "heights = [160, 170, 180]",
     "options": ["heights[1] = 175 처럼 인덱스로 지정 후 할당", "heights.change(1, 175)", "리스트는 변경할 수 없다", "heights(1) = 175"],
     "answer": 0,
     "explain": "원하는 요소를 인덱스로 지정한 후 할당 연산자로 새 값을 넣으면 됩니다. 슬라이싱으로 여러 원소를 한 번에 바꿀 수도 있습니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "nums = [3, 1, 2]\nnums.sort()\nprint(nums[-1])",
     "options": ["3", "1", "2", "[1, 2, 3]"],
     "answer": 0,
     "explain": "sort()로 [1, 2, 3]이 되고, 인덱스 -1은 마지막 항목이므로 3이 출력됩니다.",
     "difficulty": "어려움"},
    {"q": "any([0, '', 5]) 의 결과는?",
     "options": ["True", "False", "5", "오류 발생"],
     "answer": 0,
     "explain": "any()는 참인 원소가 하나라도 있으면 True입니다. 0과 ''(공백 문자열)은 False로 간주되지만 5가 참이므로 True입니다.",
     "difficulty": "어려움"},
    {"q": "다음 리스트 함축(comprehension)의 결과는?",
     "code": "result = [x for x in range(10) if x % 2 == 0]",
     "options": ["[0, 2, 4, 6, 8]", "[2, 4, 6, 8, 10]", "[1, 3, 5, 7, 9]", "[0, 1, 2, ..., 9]"],
     "answer": 0,
     "explain": "if x % 2 == 0 이 필터 역할을 해서 0~9 중 짝수만 남습니다. 수학자들이 집합을 정의하는 방식과 유사합니다.",
     "difficulty": "어려움"},
    {"q": "튜플의 가장 큰 특징은?",
     "options": ["한번 지정되면 내용을 변경할 수 없다", "숫자만 저장할 수 있다", "순서가 없다", "중복을 허용하지 않는다"],
     "answer": 0,
     "explain": "튜플은 리스트와 아주 유사하지만 한번 지정되면 변경될 수 없는 대표적인 불변(immutable) 자료형입니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 실행 결과는?",
     "code": "colors = ('red', 'green', 'blue')\ncolors[0] = 'pink'",
     "options": ["('pink', 'green', 'blue')가 된다", "에러가 발생한다", "('red', 'green', 'blue', 'pink')가 된다", "아무 일도 일어나지 않는다"],
     "answer": 1,
     "explain": "튜플은 변경될 수 없는 객체이므로 요소 변경을 시도하면 에러가 출력됩니다.",
     "difficulty": "보통"},
    {"q": "튜플을 만들 때 사용하는 기호는?",
     "options": ["( )", "[ ]", "{ }", "< >"],
     "answer": 0,
     "explain": "튜플은 소괄호로 만듭니다. 리스트는 대괄호, 딕셔너리·집합은 중괄호입니다.",
     "difficulty": "쉬움"},
    {"q": "튜플에 대한 설명으로 옳은 것은?",
     "options": ["인덱싱과 슬라이싱이 리스트와 동일하게 동작한다", "append()로 항목을 추가할 수 있다", "인덱싱이 불가능하다", "정렬하면 원본이 바뀐다"],
     "answer": 0,
     "explain": "튜플도 시퀀스의 일종이라 인덱싱·슬라이싱은 문자열이나 리스트와 동일하게 동작합니다. 다만 내용 변경(추가·수정·삭제)은 불가능합니다.",
     "difficulty": "보통"},
],

"딕셔너리와 집합": [
    {"q": "딕셔너리가 리스트와 다른 가장 큰 차이점은?",
     "options": ["값(value)과 관련된 키(key)가 있다", "더 많은 데이터를 담을 수 있다", "숫자를 담을 수 없다", "순서대로 정렬된다"],
     "answer": 0,
     "explain": "딕셔너리는 서로 관련된 키와 값을 함께 저장하며, 이를 키-값 쌍(key-value pair)이라 합니다.",
     "difficulty": "쉬움"},
    {"q": "공백(빈) 딕셔너리를 만드는 코드는?",
     "options": ["d = { }", "d = [ ]", "d = ( )", "d = dict[]"],
     "answer": 0,
     "explain": "공백 리스트는 대괄호, 공백 딕셔너리는 중괄호로 생성합니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "score = {'국어': 90, '수학': 85}\nprint(score['수학'])",
     "options": ["90", "85", "수학", "오류 발생"],
     "answer": 1,
     "explain": "딕셔너리는 키로 값을 찾습니다. score['수학']은 키 '수학'에 연결된 값 85입니다.",
     "difficulty": "쉬움"},
    {"q": "전화번호부 딕셔너리에서 값을 찾을 때 필요한 것은?",
     "code": "phone_book = {'홍길동': '010-1234', '김철수': '010-5678'}",
     "options": ["인덱스 번호", "키(사람 이름)", "값의 길이", "저장한 순서"],
     "answer": 1,
     "explain": "리스트는 인덱스로 항목을 찾지만 딕셔너리는 키가 있어야 값을 찾을 수 있습니다. phone_book['홍길동'] 처럼 사용합니다.",
     "difficulty": "보통"},
    {"q": "딕셔너리에 새 항목을 추가하는 올바른 방법은?",
     "code": "d = {'a': 1}",
     "options": ["d['b'] = 2", "d.append('b', 2)", "d.add('b': 2)", "d + {'b': 2}"],
     "answer": 0,
     "explain": "d['새키'] = 값 형태로 추가합니다. append는 리스트 전용 메소드입니다.",
     "difficulty": "보통"},
    {"q": "딕셔너리의 모든 키를 얻는 메소드는?",
     "options": ["keys()", "values()", "items()", "get()"],
     "answer": 0,
     "explain": "keys()는 모든 키, values()는 모든 값, items()는 (키, 값) 쌍을 돌려줍니다.",
     "difficulty": "보통"},
    {"q": "for 문에서 phone_book.items() 를 호출하면 무엇이 반환될까요?",
     "options": ["(키, 값) 튜플", "키만", "값만", "인덱스"],
     "answer": 0,
     "explain": "items()는 딕셔너리의 항목들을 (키, 값) 튜플 형태의 시퀀스로 추출해 줍니다.",
     "difficulty": "어려움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "d = {'x': 1, 'y': 2}\nfor k in d:\n    print(k, end=' ')",
     "options": ["1 2", "x y", "x 1 y 2", "오류 발생"],
     "answer": 1,
     "explain": "딕셔너리를 for로 돌면 키가 나옵니다. 값을 함께 보려면 items()를 사용합니다.",
     "difficulty": "어려움"},
    {"q": "리스트와 딕셔너리에서 모든 항목의 개수를 구하는 공통 함수는?",
     "options": ["len()", "count()", "size()", "total()"],
     "answer": 0,
     "explain": "둘 다 len()으로 개수를 구합니다. 지정 요소 삭제는 del, 전체 삭제는 clear()로 역시 공통입니다.",
     "difficulty": "보통"},
    {"q": "집합(set) 자료형의 특징 두 가지를 바르게 묶은 것은?",
     "options": ["순서가 없고 중복을 허용하지 않는다", "순서가 있고 중복을 허용한다", "순서가 없고 중복을 허용한다", "순서가 있고 중복을 허용하지 않는다"],
     "answer": 0,
     "explain": "집합은 수학의 집합과 비슷하게 순서가 없는 자료형이며, 동일한 값을 가지는 항목의 중복이 허용되지 않습니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "s = set([1, 2, 2, 3, 3, 3])\nprint(len(s))",
     "options": ["6", "3", "1", "오류 발생"],
     "answer": 1,
     "explain": "리스트로부터 집합을 생성하면 중복된 요소가 자동으로 제거되어 {1, 2, 3}이 됩니다.",
     "difficulty": "보통"},
    {"q": "비어 있는 집합을 만드는 올바른 코드는?",
     "options": ["s = set()", "s = { }", "s = [ ]", "s = ( )"],
     "answer": 0,
     "explain": "빈 중괄호 { }는 집합이 아니라 빈 딕셔너리가 됩니다. 비어 있는 집합은 set() 함수로 생성해야 합니다.",
     "difficulty": "어려움"},
    {"q": "{1, 2} + {1, 2, 3} 연산의 결과는?",
     "options": ["{1, 2, 3}", "{1, 1, 2, 2, 3}", "TypeError 발생", "{3}"],
     "answer": 2,
     "explain": "리스트와 달리 집합은 + 결합 연산을 지원하지 않아 TypeError가 발생합니다. 합집합은 | 연산자나 union()을 씁니다.",
     "difficulty": "보통"},
    {"q": "집합의 항목에 접근하는 방법으로 옳은 것은?",
     "options": ["in 연산자로 포함 여부 검사, for 문으로 순회", "인덱스로 접근 s[0]", "슬라이싱 s[1:3]", "키로 접근 s['a']"],
     "answer": 0,
     "explain": "집합의 항목은 순서가 없어 인덱스를 가지고 접근할 수 없습니다. in으로 포함 여부를 검사하거나 for 반복문으로 각 항목에 접근합니다.",
     "difficulty": "보통"},
    {"q": "집합에 요소를 추가/삭제하는 메소드를 차례로 고르면?",
     "options": ["add() / remove()", "append() / pop()", "insert() / del()", "push() / clear()"],
     "answer": 0,
     "explain": "집합은 add()로 요소를 추가하고 remove()로 삭제합니다. append()는 리스트 전용입니다.",
     "difficulty": "쉬움"},
    {"q": "두 집합의 합집합을 구하는 연산자/메소드는?",
     "options": ["| 또는 union()", "& 또는 intersection()", "- 또는 difference()", "+ 또는 plus()"],
     "answer": 0,
     "explain": "합집합은 | 연산자나 union() 메소드를 씁니다. 집합은 + 연산을 지원하지 않는다는 점에 주의하세요.",
     "difficulty": "보통"},
    {"q": "두 집합 a = {1, 2, 3}, b = {2, 3, 4} 의 교집합은?",
     "options": ["{1, 4}", "{2, 3}", "{1, 2, 3, 4}", "{ }"],
     "answer": 1,
     "explain": "교집합(a & b 또는 intersection())은 양쪽에 모두 들어 있는 원소만 모읍니다. 2와 3이 공통입니다.",
     "difficulty": "보통"},
    {"q": "집합에서 사용할 수 없는 연산은?",
     "options": ["len()으로 크기 구하기", "인덱싱 s[0]", "in으로 포함 검사", "max()로 최댓값 구하기"],
     "answer": 1,
     "explain": "집합의 요소에는 인덱스가 없기 때문에 인덱싱이나 슬라이싱 연산은 의미가 없습니다. len, max, min, sorted, sum 등은 사용할 수 있습니다.",
     "difficulty": "어려움"},
],
},

# ═══════════════ 파이썬 고급 v1 — 함수와 데이터 다루기 ═══════════════
"파이썬 고급 v1": {

"함수 기초": [
    {"q": "강의에서 설명한 함수(function)의 정의는?",
     "options": ["반복적으로 사용하는 코드를 묶은 것", "변수의 다른 이름", "파일을 저장하는 방법", "오류를 처리하는 문법"],
     "answer": 0,
     "explain": "함수는 반복적으로 사용하는 코드를 묶은 코드의 덩어리입니다. 파이썬에서 프로그램을 쪼개는 3가지 방법(함수·객체·모듈) 중 하나입니다.",
     "difficulty": "쉬움"},
    {"q": "함수를 정의할 때 사용하는 키워드는?",
     "options": ["def", "func", "function", "define"],
     "answer": 0,
     "explain": "def 키워드로 함수를 정의합니다. 이어서 함수 이름, 소괄호(), 콜론(:)을 붙입니다.",
     "difficulty": "쉬움"},
    {"q": "함수 정의의 올바른 형태는?",
     "options": ["def print_address():", "def print_address;", "function print_address()", "print_address() def"],
     "answer": 0,
     "explain": "def + 함수 이름 + 소괄호() + 콜론: 순서입니다. 콜론 뒤에는 들여쓰기된 함수 본문이 옵니다.",
     "difficulty": "쉬움"},
    {"q": "함수 안에 있는 코드는 언제 실행될까요?",
     "options": ["함수가 호출되어야 실행된다", "정의하는 즉시 실행된다", "프로그램 시작 시 자동 실행된다", "한 번만 실행할 수 있다"],
     "answer": 0,
     "explain": "함수 안의 코드는 자동으로 실행되지 않으며, 함수 이름과 소괄호로 호출(function call)해야 실행됩니다.",
     "difficulty": "쉬움"},
    {"q": "강의에서 함수를 비유한 표현은?",
     "options": ["입력을 받아 출력을 내보내는 블랙박스", "데이터를 담는 장바구니", "한 번 쓰고 버리는 메모지", "코드를 잠그는 자물쇠"],
     "answer": 0,
     "explain": "함수는 입력을 받아서 출력을 내보내는 블랙박스로 생각할 수 있습니다. 오렌지를 넣으면 오렌지주스가 나오는 기계처럼요.",
     "difficulty": "보통"},
    {"q": "함수를 사용하는 주된 이유는?",
     "options": ["한 번만 정의하면 필요할 때마다 불러서 일을 시킬 수 있어서", "코드가 길어져서", "변수를 안 쓰게 되어서", "실행 속도가 항상 빨라져서"],
     "answer": 0,
     "explain": "주소를 3번 출력해야 할 때 함수가 정의돼 있으면 호출 세 번이면 됩니다. 정의는 한 번, 사용은 여러 번이 함수의 핵심입니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "def greet():\n    print('안녕하세요')\n\ngreet()\ngreet()",
     "options": ["안녕하세요 2번 출력", "안녕하세요 1번 출력", "아무것도 출력 안 됨", "오류 발생"],
     "answer": 0,
     "explain": "함수를 두 번 호출했으므로 본문이 두 번 실행됩니다.",
     "difficulty": "보통"},
    {"q": "파이썬에서 프로그램을 쪼개는 3가지 방법이 아닌 것은?",
     "options": ["함수", "객체", "모듈", "엑셀"],
     "answer": 3,
     "explain": "강의에서 소개한 3가지는 함수(코드 덩어리), 객체(독립 단위 조각), 모듈(스크립트 파일)입니다.",
     "difficulty": "보통"},
],

"인자와 반환값": [
    {"q": "함수에 넘겨지는 값과 함수 내부에서 전달받는 변수를 차례로 부르는 말은?",
     "options": ["인자 / 매개변수", "매개변수 / 인자", "반환값 / 인자", "전역 변수 / 지역 변수"],
     "answer": 0,
     "explain": "함수에 넘겨지는 값이 인자(argument), 함수 내부에서 전달받는 변수가 매개변수(parameter)입니다.",
     "difficulty": "보통"},
    {"q": "함수로부터 되돌아오는 값을 부르는 말과 키워드는?",
     "options": ["반환값 / return", "결과값 / result", "출력값 / print", "전달값 / pass"],
     "answer": 0,
     "explain": "함수가 일을 마치고 우리에게 보내는 값이 반환값(return value)이며, return 키워드로 돌려줍니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "def area(radius):\n    return 3.14 * radius ** 2\n\nc_area = area(5)\nprint(c_area)",
     "options": ["78.5", "15.7", "31.4", "오류 발생"],
     "answer": 0,
     "explain": "3.14 × 5² = 78.5가 반환되어 c_area에 저장됩니다. 호출문을 할당문에 넣으면 반환값이 변수에 담깁니다.",
     "difficulty": "보통"},
    {"q": "매개변수가 2개인 함수에 인자를 1개만 주면?",
     "code": "def get_sum(start, end):\n    ...\nget_sum(1)",
     "options": ["오류가 발생한다", "나머지는 0이 된다", "정상 동작한다", "두 번 실행된다"],
     "answer": 0,
     "explain": "매개변수의 개수와 넘어가는 인자의 개수는 정확히 일치해야 합니다. 일치하지 않으면 오류가 발생합니다(디폴트 인자가 없다면).",
     "difficulty": "보통"},
    {"q": "강의에서 소개한 파이썬 함수의 큰 특징은?",
     "options": ["여러 개의 값을 반환할 수 있다", "이름 없이 정의할 수 없다", "인자를 받을 수 없다", "한 번만 호출할 수 있다"],
     "answer": 0,
     "explain": "파이썬 함수는 return a, b 처럼 여러 개의 값을 한 번에 반환할 수 있습니다.",
     "difficulty": "보통"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "def get_sum(start, end):\n    total = 0\n    for i in range(start, end + 1):\n        total += i\n    return total\n\nprint(get_sum(1, 10))",
     "options": ["55", "45", "10", "11"],
     "answer": 0,
     "explain": "1부터 10까지의 합을 계산해 반환합니다. range(start, end+1)이라 10까지 포함되어 55입니다.",
     "difficulty": "어려움"},
    {"q": "다음 코드에서 인자는 무엇일까요?",
     "code": "def print_address(name):\n    print(name, '님께')\n\nprint_address('홍길동')",
     "options": ["'홍길동'", "name", "print_address", "print"],
     "answer": 0,
     "explain": "호출할 때 함수로 넘겨주는 값 '홍길동'이 인자, 그 값을 받는 변수 name이 매개변수입니다.",
     "difficulty": "보통"},
    {"q": "return이 없는 함수의 호출 결과를 변수에 담으면?",
     "code": "def greet():\n    print('hi')\n\nx = greet()",
     "options": ["x는 None이 된다", "x는 'hi'가 된다", "오류가 발생한다", "x는 0이 된다"],
     "answer": 0,
     "explain": "반환값이 없는 함수는 None을 돌려줍니다. print는 화면 출력일 뿐 반환이 아닙니다.",
     "difficulty": "어려움"},
],

"변수의 범위와 디폴트 인자": [
    {"q": "함수 외부에서 만든 변수와 함수 내부에서 만든 변수를 차례로 부르는 말은?",
     "options": ["전역 변수 / 지역 변수", "지역 변수 / 전역 변수", "상수 / 변수", "인자 / 매개변수"],
     "answer": 0,
     "explain": "함수 외부에서 생성한 변수는 전역 변수, 함수 내부에서 생성한 변수는 지역 변수입니다.",
     "difficulty": "쉬움"},
    {"q": "다음 코드의 출력 결과는?",
     "code": "counter = 100\ndef show():\n    print(counter)\nshow()",
     "options": ["100", "0", "None", "오류 발생"],
     "answer": 0,
     "explain": "함수 내부에서 전역 변수를 읽는 것은 가능합니다. counter의 값 100이 출력됩니다.",
     "difficulty": "보통"},
    {"q": "다음 코드 실행 후 마지막 print의 출력은?",
     "code": "counter = 100\ndef change():\n    counter = 200\nchange()\nprint(counter)",
     "options": ["100", "200", "300", "오류 발생"],
     "answer": 0,
     "explain": "함수 내부의 counter = 200은 새로운 지역 변수를 만들 뿐, 외부의 전역 변수는 그대로 100입니다.",
     "difficulty": "어려움"},
    {"q": "함수 내부에서 전역 변수의 값을 바꾸려면 필요한 키워드는?",
     "options": ["global", "public", "extern", "outer"],
     "answer": 0,
     "explain": "global counter 라고 선언하면 함수 내부에서 지역 변수가 아닌 전역 변수 counter를 사용하게 됩니다.",
     "difficulty": "보통"},
    {"q": "강의에서 전역 변수 사용에 대해 주의한 내용은?",
     "options": ["너무 많이 쓰면 코드가 길어질 때 에러 발생의 원인이 된다", "쓰면 무조건 빨라진다", "함수 안에서는 절대 읽을 수 없다", "숫자만 저장할 수 있다"],
     "answer": 0,
     "explain": "전역 변수를 너무 많이 사용하면 코드가 길어질 경우 에러 발생의 원인이 되니 꼭 필요한 곳에만 쓰라고 강조합니다.",
     "difficulty": "보통"},
    {"q": "함수의 매개변수가 기본값을 가지는 것을 무엇이라 할까요?",
     "options": ["디폴트 인자", "키워드 인자", "위치 인자", "가변 인자"],
     "answer": 0,
     "explain": "디폴트 인자(default argument)는 인자가 부족할 때 기본값을 넣어 주는 메커니즘입니다.",
     "difficulty": "쉬움"},
    {"q": "다음 함수를 order()로 호출하면 pickle 값은?",
     "code": "def order(pickle=True, onion=True):\n    ...",
     "options": ["True", "False", "None", "오류 발생"],
     "answer": 0,
     "explain": "인자를 생략하면 디폴트 인자 True가 사용됩니다. 인자가 부족해도 오류가 나지 않는 것이 디폴트 인자의 장점입니다.",
     "difficulty": "보통"},
    {"q": "power(base=2, exponent=10) 처럼 이름을 명시해 전달하는 인자를 부르는 말은?",
     "options": ["키워드 인자", "디폴트 인자", "전역 인자", "복합 인자"],
     "answer": 0,
     "explain": "키워드 인자는 매개변수 이름을 명시하므로 위치가 헷갈리지 않습니다. power(2, 10)은 위치로 구별되는 위치 인자입니다.",
     "difficulty": "보통"},
    {"q": "인자의 순서 규칙으로 옳은 것은?",
     "options": ["위치 인자가 먼저, 키워드 인자가 나중", "키워드 인자가 먼저, 위치 인자가 나중", "순서는 상관없다", "키워드 인자는 하나만 가능"],
     "answer": 0,
     "explain": "위치 인자는 언제나 키워드 인자보다 먼저 나와야 합니다. 키워드 인자 뒤에 위치 인자를 쓰면 오류입니다.",
     "difficulty": "어려움"},
    {"q": "함수 내부에서 자기 자신을 호출하는 함수를 무엇이라 할까요?",
     "options": ["재귀 함수", "내장 함수", "익명 함수", "중첩 함수"],
     "answer": 0,
     "explain": "재귀(recursion) 함수는 자기 자신을 호출하며, 팩토리얼처럼 절차적으로 풀기 어려운 문제를 직관적으로 해결합니다.",
     "difficulty": "쉬움"},
    {"q": "재귀 함수에서 가장 중요한 점으로 강의가 강조한 것은?",
     "options": ["언제 종료되는가(종료 조건)", "얼마나 빠른가", "몇 줄인가", "이름이 짧은가"],
     "answer": 0,
     "explain": "재귀 함수는 종료 조건이 중요합니다. 팩토리얼은 1! = 1이라는 정의가 종료 조건이 됩니다.",
     "difficulty": "보통"},
],

"판다스와 CSV": [
    {"q": "CSV는 무엇의 약자일까요?",
     "options": ["comma separated variables", "computer saved values", "column sorted values", "code separated variables"],
     "answer": 0,
     "explain": "CSV는 쉼표로 구분한 변수(comma separated variables)의 약자로, 표 형식 데이터를 저장·이동하는 텍스트 파일 형식입니다.",
     "difficulty": "쉬움"},
    {"q": "CSV 파일의 구조로 옳은 것은?",
     "options": ["열은 필드, 행은 레코드", "열은 레코드, 행은 필드", "열과 행 모두 레코드", "구조가 없다"],
     "answer": 0,
     "explain": "CSV 파일은 필드를 나타내는 열과 레코드를 나타내는 행으로 구성됩니다.",
     "difficulty": "보통"},
    {"q": "'Gildong, Hong'처럼 데이터 중간에 쉼표가 들어가야 한다면?",
     "options": ["따옴표로 필드를 묶는다", "쉼표를 삭제한다", "공백으로 바꾼다", "저장할 수 없다"],
     "answer": 0,
     "explain": "데이터 중간에 구분자(쉼표)가 포함되면 따옴표를 사용하여 필드를 묶어야 합니다.",
     "difficulty": "보통"},
    {"q": "csv 모듈로 읽을 때 헤더(첫 줄)를 건너뛰는 함수는?",
     "options": ["next()", "skip()", "pass()", "head()"],
     "answer": 0,
     "explain": "next() 함수를 한 번 호출하면 첫 행(헤더)을 건너뛰고 데이터부터 읽을 수 있습니다.",
     "difficulty": "보통"},
    {"q": "판다스(Pandas)에 대한 설명으로 옳은 것은?",
     "options": ["데이터 분석 라이브러리로 CSV·엑셀 파일을 열 수 있다", "그림을 그리는 전용 도구다", "파이썬 기본 문법이다", "웹 브라우저다"],
     "answer": 0,
     "explain": "판다스는 리스트·딕셔너리·넘파이 배열을 데이터프레임으로 변환하고, CSV나 엑셀 파일을 열 수 있는 데이터 분석 라이브러리입니다.",
     "difficulty": "쉬움"},
    {"q": "판다스에서 열 사이의 상관관계를 계산하는 함수는?",
     "options": ["corr()", "mean()", "count()", "sum()"],
     "answer": 0,
     "explain": "corr()는 데이터프레임 열 사이의 상관관계, mean()은 평균, count()는 데이터 개수를 계산합니다.",
     "difficulty": "어려움"},
    {"q": "강의에서 설명한 모듈(module)이란?",
     "options": ["함수나 변수, 클래스들을 모아 놓은 스크립트 파일", "변수의 다른 이름", "에러 메시지 모음", "주석의 한 종류"],
     "answer": 0,
     "explain": "모듈은 파이썬 함수·변수·클래스들을 모아 놓은 스크립트 파일이며, 이를 이용해 효과적으로 소프트웨어를 개발할 수 있습니다.",
     "difficulty": "쉬움"},
    {"q": "넘파이가 있는데도 판다스를 쓰는 이유로 강의가 든 것은?",
     "options": ["다양한 속성의 데이터를 표 형태로 다루기 좋아서", "넘파이보다 무조건 빨라서", "글자를 못 쓰는 넘파이와 달리 숫자만 다뤄서", "설치가 필요 없어서"],
     "answer": 0,
     "explain": "넘파이는 2차원 행렬 형태를 지원하지만, 엑셀처럼 다양한 속성의 표 데이터를 다루는 데는 판다스가 탁월합니다.",
     "difficulty": "어려움"},
],

"데이터프레임 다루기": [
    {"q": "판다스가 데이터 저장을 위해 제공하는 2가지 기본 데이터 구조는?",
     "options": ["시리즈와 데이터프레임", "리스트와 튜플", "배열과 행렬", "딕셔너리와 집합"],
     "answer": 0,
     "explain": "판다스의 기본 구조는 1차원의 시리즈(Series)와 2차원의 데이터프레임(DataFrame)입니다.",
     "difficulty": "쉬움"},
    {"q": "np.nan 이 의미하는 것은?",
     "options": ["값 없음(Not a Number)", "0", "무한대", "음수"],
     "answer": 0,
     "explain": "np.nan은 수치 데이터가 없을 때 이를 표기하는 방법으로, '값 없음'을 의미합니다.",
     "difficulty": "보통"},
    {"q": "CSV 파일을 읽어 데이터프레임으로 만드는 판다스 함수는?",
     "options": ["read_csv()", "open_csv()", "load_file()", "csv_read()"],
     "answer": 0,
     "explain": "pd.read_csv('파일명') 한 줄이면 CSV가 데이터프레임으로 변환됩니다.",
     "difficulty": "쉬움"},
    {"q": "데이터프레임 df에서 'population' 열만 선택하는 코드는?",
     "options": ["df['population']", "df.get_row('population')", "df(population)", "df->population"],
     "answer": 0,
     "explain": "대괄호 안에 열의 이름을 넣으면 특정 열만 선택됩니다. 여러 열은 레이블 리스트를 전달합니다.",
     "difficulty": "보통"},
    {"q": "데이터프레임의 처음 5행과 마지막 5행을 보는 함수를 차례로 고르면?",
     "options": ["head() / tail()", "top() / bottom()", "first() / last()", "begin() / end()"],
     "answer": 0,
     "explain": "head()는 처음 5행, tail()은 마지막 5행을 가져옵니다.",
     "difficulty": "쉬움"},
    {"q": "행과 열의 레이블로 특정 요소 하나를 선택할 때 쓰는 속성은?",
     "options": ["loc", "pos", "cell", "at_index"],
     "answer": 0,
     "explain": "df.loc['KR'] 처럼 loc 속성에 행과 열의 레이블을 써 주면 특정 행이나 요소를 선택할 수 있습니다.",
     "difficulty": "보통"},
    {"q": "선택한 열을 그래프로 그리려면 데이터프레임 이름 뒤에 무엇을 붙일까요?",
     "options": [".plot()", ".draw()", ".graph()", ".show()"],
     "answer": 0,
     "explain": "데이터프레임 이름 다음에 plot() 메소드만 추가하면 선택된 열을 그래프로 그릴 수 있습니다.",
     "difficulty": "보통"},
    {"q": "데이터프레임의 데이터 특성을 전체적으로 요약해 주는 함수는?",
     "options": ["describe()", "summary()", "info_all()", "preview()"],
     "answer": 0,
     "explain": "describe() 함수를 호출하면 평균, 표준편차 등 데이터의 특징을 한 번에 요약해 줍니다.",
     "difficulty": "쉬움"},
    {"q": "결손값(빠진 값)이 있는지 확인하는 함수는?",
     "options": ["isna()", "empty()", "isnull_check()", "missing()"],
     "answer": 0,
     "explain": "isna()로 결손값 여부를 확인할 수 있습니다. weather['평균풍속'].isna() 처럼 사용합니다.",
     "difficulty": "보통"},
    {"q": "결손값을 0으로 채우면서 원본에 바로 반영하려면?",
     "options": ["fillna(0, inplace=True)", "fillna(0)만 쓰면 된다", "replace(0)", "setna(0)"],
     "answer": 0,
     "explain": "fillna()가 결손값을 채우는 함수이고, inplace=True 옵션을 줘야 원본 데이터프레임에 반영됩니다.",
     "difficulty": "어려움"},
    {"q": "데이터프레임을 특정 열 기준으로 정렬하는 함수는?",
     "options": ["sort_values()", "order_by()", "arrange()", "sort_list()"],
     "answer": 0,
     "explain": "sort_values() 함수에 정렬할 열의 이름을 인자로 주면 됩니다.",
     "difficulty": "보통"},
    {"q": "나누어져 있는 데이터프레임들을 합치는 함수는?",
     "options": ["concat()", "merge_all()", "join_df()", "plus()"],
     "answer": 0,
     "explain": "데이터는 작은 테이블로 나뉘어 있는 경우가 많은데, concat() 함수로 데이터프레임을 합칠 수 있습니다.",
     "difficulty": "보통"},
    {"q": "weather 데이터프레임에서 '최대풍속'이 10.0을 넘는 행만 추리는 코드는?",
     "options": ["weather[ weather['최대풍속'] > 10.0 ]", "weather.filter(10.0)", "weather > 10.0 만 쓰면 된다", "weather.where('최대풍속')"],
     "answer": 0,
     "explain": "비교 연산으로 True/False를 얻고 그 결과를 대괄호 안에 넣으면 조건에 맞는 행만 추려집니다. 넘파이의 논리 인덱싱과 동일한 문법입니다.",
     "difficulty": "어려움"},
],
},

# ═══════════════ 파이썬 고급 v2 — 넘파이 ═══════════════
"파이썬 고급 v2": {

"넘파이 기초": [
    {"q": "넘파이(NumPy)에 대한 설명으로 옳은 것은?",
     "options": ["대용량 배열·행렬 연산을 빠르게 수행하는 라이브러리", "웹사이트를 만드는 프레임워크", "그림판 프로그램", "파이썬 설치 도구"],
     "answer": 0,
     "explain": "넘파이는 대용량의 배열과 행렬 연산을 빠르게 수행하며, 고차원적인 수학 연산자와 함수를 포함한 파이썬 라이브러리입니다.",
     "difficulty": "쉬움"},
    {"q": "넘파이를 보통 어떤 별칭으로 불러올까요?",
     "options": ["import numpy as np", "import numpy as num", "import np as numpy", "using numpy"],
     "answer": 0,
     "explain": "import ~ as 구문으로 별칭을 붙입니다. 관례적으로 numpy의 별칭은 np를 사용합니다.",
     "difficulty": "쉬움"},
    {"q": "파이썬 리스트 [10, 20] + [30, 40] 의 결과는?",
     "options": ["[10, 20, 30, 40]", "[40, 60]", "[10, 20], [30, 40]", "오류 발생"],
     "answer": 0,
     "explain": "리스트의 + 는 두 리스트를 연결합니다. 원소끼리 더하고 싶다면 넘파이 배열이 필요합니다.",
     "difficulty": "보통"},
    {"q": "넘파이 배열 np.array([10, 20]) + np.array([30, 40]) 의 결과는?",
     "options": ["[40, 60]", "[10, 20, 30, 40]", "[300, 800]", "오류 발생"],
     "answer": 0,
     "explain": "넘파이의 덧셈은 차원이 같은 두 벡터의 원소들끼리 더하는 벡터합 연산입니다.",
     "difficulty": "보통"},
    {"q": "전통적인 의미의 배열(array)이란?",
     "options": ["동일한 자료형의 데이터를 연속적으로 저장한 것", "서로 다른 자료형을 자유롭게 담는 것", "키와 값의 쌍", "정렬된 문자열"],
     "answer": 0,
     "explain": "배열은 동일한 자료형을 가진 데이터를 연속적으로 저장합니다. 넘파이의 ndarray가 이런 구조입니다.",
     "difficulty": "보통"},
    {"q": "데이터 분석·기계학습에서 넘파이 이해가 필수인 이유는?",
     "options": ["판다스, Scikit-learn, Tensorflow 등이 넘파이를 기반으로 하기 때문", "넘파이 없이는 파이썬이 실행되지 않아서", "넘파이가 유일한 라이브러리라서", "법으로 정해져 있어서"],
     "answer": 0,
     "explain": "판다스·Scikit-learn·Tensorflow 같은 핵심 패키지들이 넘파이를 기반으로 하므로 확실한 이해가 필수입니다.",
     "difficulty": "보통"},
    {"q": "넘파이 배열과 파이썬 리스트의 차이로 옳은 것은?",
     "options": ["넘파이 배열은 각 배열마다 타입을 하나만 가진다", "리스트가 항상 더 빠르다", "넘파이 배열은 인덱싱이 안 된다", "리스트는 숫자만 담을 수 있다"],
     "answer": 0,
     "explain": "리스트는 다양한 자료형을 섞어 담을 수 있지만, 넘파이 배열은 타입이 하나라 처리 속도가 빠릅니다.",
     "difficulty": "보통"},
    {"q": "넘파이 배열이 리스트보다 빠른 이유는?",
     "options": ["동일 자료형이라 저장 공간이 일정해 위치만 알면 바로 접근할 수 있어서", "컴퓨터를 두 대 사용해서", "데이터를 절반만 저장해서", "그래픽카드가 필수라서"],
     "answer": 0,
     "explain": "동일한 자료형으로만 저장하면 각 항목의 저장 공간이 일정해, 몇 번째 항목이든 순서만 알면 바로 접근할 수 있습니다.",
     "difficulty": "어려움"},
    {"q": "성적 합산 예제에서 학생별 총점을 구하려면?",
     "code": "mid = np.array([10, 20, 30])\nfinal = np.array([70, 80, 90])",
     "options": ["mid + final", "mid.append(final)", "mid & final", "sum(mid, final)"],
     "answer": 0,
     "explain": "넘파이 배열끼리 더하면 원소끼리 더해져 [80, 100, 120]처럼 학생별 총점이 나옵니다.",
     "difficulty": "쉬움"},
],

"배열 속성과 연산": [
    {"q": "전 직원의 월급 배열 salary에 100을 더하면?",
     "code": "salary = np.array([220, 250, 230])\nsalary + 100",
     "options": ["모든 요소에 100이 더해진다", "첫 요소에만 더해진다", "오류가 발생한다", "배열 길이가 1 늘어난다"],
     "answer": 0,
     "explain": "넘파이 배열에 수를 더하면 배열의 모든 요소에 그 수가 더해집니다. [320, 350, 330]이 됩니다.",
     "difficulty": "쉬움"},
    {"q": "모든 직원의 월급을 2배로 올리려면?",
     "code": "salary = np.array([220, 250, 230])",
     "options": ["salary * 2", "salary.double()", "salary + salary[0]", "2 in salary"],
     "answer": 0,
     "explain": "배열에 2를 곱하면 모든 요소가 2배가 됩니다. + 나 * 같은 수학 연산자를 얼마든지 적용할 수 있습니다.",
     "difficulty": "쉬움"},
    {"q": "넘파이 배열의 모든 항목에 대한 규칙은?",
     "options": ["동일한 자료형을 가져야 한다", "서로 달라야 한다", "문자열은 안 된다", "10개 이하여야 한다"],
     "answer": 0,
     "explain": "파이썬 리스트와 달리 넘파이 배열은 모든 항목이 동일한 자료형을 가집니다.",
     "difficulty": "쉬움"},
    {"q": "정수 넘파이 배열의 요소에 3.7을 할당하면?",
     "code": "arr = np.array([1, 2, 3])\narr[0] = 3.7",
     "options": ["소수점이 버려져 3이 저장된다", "3.7이 그대로 저장된다", "오류가 발생한다", "배열 전체가 실수가 된다"],
     "answer": 0,
     "explain": "배열의 자료형(정수)이 유지되어야 하므로 부동소수점을 넣으면 소수점 이하가 버려집니다.",
     "difficulty": "어려움"},
    {"q": "코드의 수행 시간을 측정할 때 사용하는 모듈과 함수는?",
     "options": ["time 모듈의 time()", "math 모듈의 clock()", "random 모듈의 timer()", "sys 모듈의 watch()"],
     "answer": 0,
     "explain": "time 모듈의 time() 함수는 현재 컴퓨터의 시간을 밀리초 단위로 알아낼 수 있어 수행 시간 측정에 쓰입니다.",
     "difficulty": "보통"},
    {"q": "반복문 합산과 np.sum() 벡터화 연산을 비교한 강의 실험의 결과는?",
     "options": ["벡터화 연산이 훨씬 빨랐다(0.023초 vs 0.00065초)", "반복문이 더 빨랐다", "둘이 똑같았다", "둘 다 실행되지 않았다"],
     "answer": 0,
     "explain": "같은 합 연산이 반복문으로는 0.023초, np.sum() 벡터화 연산으로는 0.00065초로 수십 배 빨랐습니다.",
     "difficulty": "보통"},
    {"q": "벡터화 연산이란?",
     "options": ["반복문 없이 배열 전체에 연산을 한 번에 적용하는 것", "벡터 그림을 그리는 것", "배열을 반드시 1차원으로 만드는 것", "데이터를 압축하는 것"],
     "answer": 0,
     "explain": "벡터화 연산은 배열 전체에 연산을 한 번에 적용하는 넘파이의 장점으로, 반복문보다 훨씬 빠릅니다.",
     "difficulty": "보통"},
    {"q": "ndarray의 속성을 활용하면 좋은 점은?",
     "options": ["프로그램의 오류를 찾거나 배열의 상세 정보를 쉽게 조회할 수 있다", "배열이 자동으로 정렬된다", "메모리가 두 배가 된다", "출력이 예뻐진다"],
     "answer": 0,
     "explain": "다차원 배열 ndarray의 속성들을 이용하면 오류를 찾거나 배열의 상세한 정보를 손쉽게 조회할 수 있습니다.",
     "difficulty": "보통"},
],

"인덱싱과 슬라이싱": [
    {"q": "넘파이 배열의 인덱스는 몇 번부터 시작할까요?",
     "options": ["0", "1", "-1", "원하는 수"],
     "answer": 0,
     "explain": "파이썬 리스트와 마찬가지로 넘파이 배열의 인덱스도 0부터 시작합니다.",
     "difficulty": "쉬움"},
    {"q": "scores[1:3] 슬라이싱이 가져오는 요소는?",
     "options": ["인덱스 1과 2", "인덱스 1, 2, 3", "인덱스 2와 3", "처음 3개"],
     "answer": 0,
     "explain": "마지막 인덱스가 3이면 3-1인 scores[2] 항목까지 슬라이싱됩니다.",
     "difficulty": "보통"},
    {"q": "조건을 주어 배열에서 원하는 값을 추려내는 것을 무엇이라 할까요?",
     "options": ["논리적인 인덱싱", "이중 인덱싱", "역순 인덱싱", "무작위 인덱싱"],
     "answer": 0,
     "explain": "논리적인 인덱싱(logical indexing)은 ages > 20 같은 조건으로 원하는 값을 추려내는 방법입니다.",
     "difficulty": "쉬움"},
    {"q": "ages > 20 연산의 결과는?",
     "code": "ages = np.array([18, 19, 25, 30, 28])",
     "options": ["True/False로 이루어진 부울형 배열", "20보다 큰 값들만", "가장 큰 값 하나", "오류 발생"],
     "answer": 0,
     "explain": "비교 연산의 결과는 [False, False, True, True, True] 같은 부울형 넘파이 배열입니다.",
     "difficulty": "보통"},
    {"q": "20살 이상인 사람들의 나이 값 자체를 뽑아내는 코드는?",
     "code": "ages = np.array([18, 19, 25, 30, 28])",
     "options": ["ages[ages > 20]", "ages > 20", "ages.pick(20)", "ages[20]"],
     "answer": 0,
     "explain": "부울 배열을 대괄호 안에 넣으면 True인 위치의 값들만 추려집니다. [25, 30, 28]이 나옵니다.",
     "difficulty": "보통"},
    {"q": "2차원 배열에서 요소를 꺼낼 때 필요한 인덱스 개수는?",
     "options": ["2개 (행 번호, 열 번호)", "1개", "3개", "필요 없다"],
     "answer": 0,
     "explain": "2차원이기 때문에 인덱스가 2개 필요합니다. 첫 번째는 행 번호, 두 번째는 열 번호입니다.",
     "difficulty": "쉬움"},
    {"q": "0번째 행, 2번째 열 요소에 접근하는 넘파이에서 많이 쓰는 표기는?",
     "options": ["np_array[0, 2]", "np_array(0, 2)", "np_array{0, 2}", "np_array[2, 0]"],
     "answer": 0,
     "explain": "np_array[0][2]도 가능하지만, 넘파이에서는 콤마를 사용한 [행, 열] 표기를 많이 사용합니다.",
     "difficulty": "보통"},
    {"q": "넘파이 2차원 배열은 수학의 무엇에 해당할까요?",
     "options": ["행렬(matrix)", "집합", "수열", "함수"],
     "answer": 0,
     "explain": "2차원 넘파이 배열은 행렬입니다. 역행렬, 행렬식 같은 행렬 연산이 쉽게 적용되도록 구현돼 있습니다.",
     "difficulty": "쉬움"},
    {"q": "2차원 배열에서 슬라이싱이란?",
     "options": ["큰 행렬에서 작은 행렬을 끄집어내는 것", "행렬을 회전하는 것", "행렬을 저장하는 것", "행렬을 출력하는 것"],
     "answer": 0,
     "explain": "넘파이 2차원 슬라이싱은 큰 행렬에서 작은 행렬을 추출하는 것으로 이해하면 됩니다.",
     "difficulty": "보통"},
    {"q": "np_array > 5 를 2차원 배열에 적용하면?",
     "code": "np_array = np.array([[1,2,3],[4,5,6],[7,8,9]])",
     "options": ["True/False로 이루어진 같은 모양의 배열", "5보다 큰 수의 개수", "마지막 행만", "오류 발생"],
     "answer": 0,
     "explain": "2차원 배열에도 비교 연산자를 쓰면 True, False로 이루어진 배열이 반환되고, 이를 이용해 특정 값들을 뽑아낼 수 있습니다.",
     "difficulty": "어려움"},
    {"q": "2차원 배열에서 짝수만 골라내는 조건은?",
     "options": ["np_array % 2 == 0", "np_array // 2", "np_array.even()", "np_array / 2 == 0"],
     "answer": 0,
     "explain": "%2의 결과가 0인 곳이 짝수이므로, 짝수 위치만 True인 부울 배열을 얻어 값을 추려낼 수 있습니다.",
     "difficulty": "어려움"},
],

"배열 생성 함수": [
    {"q": "np.arange(5) 와 비슷한 동작을 하는 파이썬 기본 함수는?",
     "options": ["range()", "len()", "list()", "input()"],
     "answer": 0,
     "explain": "arange()는 for 문에서 쓰던 range()와 비슷하지만, 결과로 넘파이 배열(ndarray)을 돌려준다는 점이 다릅니다.",
     "difficulty": "쉬움"},
    {"q": "linspace(0, 10, 100) 이 생성하는 것은?",
     "options": ["0에서 10까지 균일한 간격의 수 100개", "0에서 100까지 10개", "10의 배수 100개", "무작위 수 100개"],
     "answer": 0,
     "explain": "linspace()는 시작값부터 끝값까지 균일한 간격으로 지정된 개수만큼의 배열을 생성하는, 상당히 많이 쓰이는 함수입니다.",
     "difficulty": "보통"},
    {"q": "로그 스케일로 수들을 생성하는 함수는?",
     "options": ["logspace()", "linspace()", "logrange()", "expspace()"],
     "answer": 0,
     "explain": "logspace()는 linspace()와 비슷하지만 로그 스케일로 수들을 생성합니다.",
     "difficulty": "보통"},
    {"q": "reshape() 함수가 하는 일은?",
     "options": ["데이터 개수는 유지한 채 배열의 차원과 형태를 변경", "데이터를 삭제", "배열을 정렬", "난수를 생성"],
     "answer": 0,
     "explain": "reshape()는 데이터의 개수는 유지하면서 배열의 차원과 형태만 바꿉니다. shape을 튜플로 넘겨줍니다.",
     "difficulty": "쉬움"},
    {"q": "flatten() 함수가 하는 일은?",
     "options": ["고차원 배열을 1차원 배열로 만든다", "배열을 2배로 늘린다", "배열을 뒤집는다", "0을 제거한다"],
     "answer": 0,
     "explain": "flatten()은 평탄화 함수로, 2차원 이상의 고차원 배열을 1차원 배열로 만들어 줍니다.",
     "difficulty": "보통"},
    {"q": "reshape(-1) 처럼 -1을 전달하면?",
     "options": ["데이터 개수에 맞춰 배열 형태가 자동으로 결정된다", "배열이 거꾸로 뒤집힌다", "마지막 요소가 삭제된다", "오류가 발생한다"],
     "answer": 0,
     "explain": "인수로 -1을 전달하면 데이터의 개수에 맞춰서 자동으로 배열의 형태가 결정됩니다.",
     "difficulty": "어려움"},
    {"q": "np.arange(1, 10, 2) 가 만드는 배열은?",
     "options": ["[1, 3, 5, 7, 9]", "[1, 2, 3, ..., 9]", "[2, 4, 6, 8]", "[1, 10, 2]"],
     "answer": 0,
     "explain": "arange(시작, 끝, 증가폭)으로 1부터 10 직전까지 2씩 커지는 배열을 만듭니다.",
     "difficulty": "보통"},
    {"q": "12개의 데이터를 3행 4열로 바꾸는 코드는?",
     "code": "arr = np.arange(12)",
     "options": ["arr.reshape((3, 4))", "arr.resize(3+4)", "arr.split(3, 4)", "arr.matrix(12)"],
     "answer": 0,
     "explain": "reshape()의 인자인 shape을 (3, 4) 튜플 형태로 넘겨주면 3행 4열 배열이 됩니다.",
     "difficulty": "보통"},
],

"난수와 통계": [
    {"q": "데이터 과학자가 1만 개 이상의 실험 데이터를 만들 때 사용하는 방법은?",
     "options": ["난수 생성", "직접 입력", "복사·붙여넣기", "종이에 기록"],
     "answer": 0,
     "explain": "수만 개의 데이터를 직접 입력할 수는 없으므로 난수를 생성해 데이터를 만듭니다.",
     "difficulty": "쉬움"},
    {"q": "난수의 시드(seed)를 설정하는 이유는?",
     "options": ["같은 난수를 재현할 수 있게 하려고", "난수를 더 무작위로 만들려고", "난수의 크기를 키우려고", "메모리를 아끼려고"],
     "answer": 0,
     "explain": "컴퓨터의 난수는 규칙을 가지고 생성되므로, 시드를 설정하면 같은 난수열을 다시 얻을 수 있습니다.",
     "difficulty": "보통"},
    {"q": "np.random.randint(1, 11, (4, 7)) 이 생성하는 것은?",
     "options": ["1부터 10 사이의 4행 7열 난수", "1부터 11 사이의 7행 4열 난수", "4부터 7 사이의 난수 11개", "0과 1 사이의 실수"],
     "answer": 0,
     "explain": "1부터 (11-1)=10 사이의 정수 난수를 4행 7열 배열로 생성합니다.",
     "difficulty": "어려움"},
    {"q": "정규분포에 대한 설명으로 옳은 것은?",
     "options": ["평균값에서 발생 확률이 가장 높고 멀수록 낮아진다", "모든 값의 확률이 똑같다", "0과 1만 나온다", "음수만 나온다"],
     "answer": 0,
     "explain": "정규분포는 평균값에서 가장 높고 평균에서 멀수록 발생 확률이 낮아지는 분포입니다.",
     "difficulty": "보통"},
    {"q": "표준편차(σ)가 크면 어떻게 될까요?",
     "options": ["데이터의 흩어짐이 커진다", "데이터가 한 점에 모인다", "평균이 커진다", "데이터 개수가 늘어난다"],
     "answer": 0,
     "explain": "표준편차가 클수록 데이터의 흩어짐이 커서 발생 확률이 평평하게 펴진 상태에 접근합니다.",
     "difficulty": "보통"},
    {"q": "평균 175, 표준편차 10인 키 데이터 10,000개를 만드는 코드는?",
     "options": ["np.random.normal(175, 10, 10000)", "np.random.rand(175, 10)", "np.random.randint(10000)", "np.normal(10000)"],
     "answer": 0,
     "explain": "normal(평균, 표준편차, 개수)로 정규분포를 따르는 난수를 생성합니다.",
     "difficulty": "어려움"},
    {"q": "중앙값(median)이란?",
     "options": ["크기순으로 나열했을 때 중앙에 있는 항목", "가장 많이 나온 값", "최댓값과 최솟값의 평균", "모든 값의 합"],
     "answer": 0,
     "explain": "중앙값은 리스트의 중앙에 있는 항목입니다. 평균과 함께 데이터의 특징을 보여 주는 대표값입니다.",
     "difficulty": "보통"},
    {"q": "두 데이터의 상관관계를 계산하는 넘파이 함수는?",
     "options": ["corrcoef(x, y)", "correlate_all()", "relation()", "compare(x, y)"],
     "answer": 0,
     "explain": "corrcoef(x, y)는 요소들의 상관관계를 계산합니다. x와 y는 데이터를 담은 리스트나 배열입니다.",
     "difficulty": "보통"},
    {"q": "x값이 증가할 때 y값도 함께 증가한다면 둘의 상관관계는?",
     "options": ["매우 높다", "매우 낮다", "0이다", "음수다"],
     "answer": 0,
     "explain": "키가 큰 사람이 몸무게도 많이 나가는 것처럼, 한 값이 증가할 때 다른 값도 증가하면 상관관계가 매우 높습니다.",
     "difficulty": "쉬움"},
],
},
}
